/* Copyright (c) 2006, Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

options {
  JAVA_UNICODE_ESCAPE = true;
  UNICODE_INPUT  = true;
  ERROR_REPORTING = false;
  STATIC = false;
  COMMON_TOKEN_ACTION = false;
  TOKEN_FACTORY = "cat.quadriga.parsers.tokens.MySimpleToken";
  JDK_VERSION = "1.5";
}

PARSER_BEGIN(QuadrigaSimple)
package cat.quadriga.parsers;

import java.io.*;
import java.util.*;
import cat.quadriga.parsers.code.*;
import cat.quadriga.parsers.code.expressions.*;
import cat.quadriga.parsers.code.expressions.dataaccess.*;
import cat.quadriga.parsers.code.expressions.qdg.*;
import cat.quadriga.parsers.code.printers.*;
import cat.quadriga.parsers.code.proxy.*;
import cat.quadriga.parsers.code.statements.*;
import cat.quadriga.parsers.code.statements.qdg.*;
import cat.quadriga.parsers.code.symbols.*;
import cat.quadriga.parsers.code.types.*;
import cat.quadriga.parsers.code.types.qdg.*;

/**
 * Grammar to parse Java version 1.5
 * @author Sreenivasa Viswanadha - Simplified and enhanced for 1.5
 */
public class QuadrigaSimple
{
   /**
    * Class to hold modifiers.
    */
   static public final class ModifierSet
   {
     /* Definitions of the bits in the modifiers field.  */
     public static final int PUBLIC = 0x0001;
     public static final int PROTECTED = 0x0002;
     public static final int PRIVATE = 0x0004;
     public static final int ABSTRACT = 0x0008;
     public static final int STATIC = 0x0010;
     public static final int FINAL = 0x0020;
     public static final int SYNCHRONIZED = 0x0040;
     public static final int NATIVE = 0x0080;
     public static final int TRANSIENT = 0x0100;
     public static final int VOLATILE = 0x0200;
     public static final int STRICTFP = 0x1000;

     /** A set of accessors that indicate whether the specified modifier
         is in the set. */

     public boolean isPublic(int modifiers)
     {
       return (modifiers & PUBLIC) != 0;
     }

     public boolean isProtected(int modifiers)
     {
       return (modifiers & PROTECTED) != 0;
     }

     public boolean isPrivate(int modifiers)
     {
       return (modifiers & PRIVATE) != 0;
     }

     public boolean isStatic(int modifiers)
     {
       return (modifiers & STATIC) != 0;
     }

     public boolean isAbstract(int modifiers)
     {
       return (modifiers & ABSTRACT) != 0;
     }

     public boolean isFinal(int modifiers)
     {
       return (modifiers & FINAL) != 0;
     }

     public boolean isNative(int modifiers)
     {
       return (modifiers & NATIVE) != 0;
     }

     public boolean isStrictfp(int modifiers)
     {
       return (modifiers & STRICTFP) != 0;
     }

     public boolean isSynchronized(int modifiers)
     {
       return (modifiers & SYNCHRONIZED) != 0;
     }

     public boolean isTransient(int modifiers)
      {
       return (modifiers & TRANSIENT) != 0;
     }

     public boolean isVolatile(int modifiers)
     {
       return (modifiers & VOLATILE) != 0;
     }

     /**
      * Removes the given modifier.
      */
     static int removeModifier(int modifiers, int mod)
     {
        return modifiers & ~mod;
     }
   }

   private int id = 0;

   private int getNewId()   {     return id++;
   }

   public ErrorLog errorLog = new ErrorLog();

   public final SymbolTable symbolTable = new SymbolTable();

   private BlockCode.TmpBlockCode localBlock = null;

   private String currentFile;

   private Set<String> dependencies = new HashSet<String>();

   private String file;

   private void addDependency(String dependency) {
     if(dependency != null
        && currentFile.compareTo(dependency) != 0
        && !dependencies.contains(dependency)
       )
     {
       dependencies.add( dependency );       }   }

   public Set<String> getDependences() {
     return Collections.unmodifiableSet(dependencies);   }

   public QuadrigaSimple(String fileName)
   {
      this(System.in);
      try { ReInit(new FileInputStream(new File(fileName))); }
      catch(Exception e) { e.printStackTrace(); }
      file = fileName;
   }

  public static void main(String args[]) {
    QuadrigaSimple parser;
    if (args.length == 0) {
      System.out.println("Java Parser Version 1.1:  Reading from standard input . . .");
      parser = new QuadrigaSimple(System.in);
    } else if (args.length == 1) {
      System.out.println("Java Parser Version 1.1:  Reading from file " + args[0] + " . . .");
      try {
        parser = new QuadrigaSimple(new java.io.FileInputStream(args[0]), "UTF-8");
      } catch (java.io.FileNotFoundException e) {
        System.out.println("Java Parser Version 1.1:  File " + args[0] + " not found.");
        return;
      }
    } else {
      System.out.println("Java Parser Version 1.1:  Usage is one of:");
      System.out.println("         java JavaParser < inputfile");
      System.out.println("OR");
      System.out.println("         java JavaParser inputfile");
      return;
    }
    try {
      List<PrintInfo> info = parser.CompilationUnit();
      System.out.println("Java Parser Version 1.1:  Java program parsed successfully.");
      MegaPrinter mp = MegaPrinter.getInstance();
      System.out.println(mp.print(info));
      mp.printToFile(info, "out.java");
    } catch (ParseException e) {
      System.out.println(e.getMessage());
      System.out.println("Java Parser Version 1.1:  Encountered errors during parse.");
    }
  }

  

}

class VarAndInit{  Token name;
  BaseType type;
  StatementNode init;
  int modifiers;
}

PARSER_END(QuadrigaSimple)

/* WHITE SPACE */

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
| "\f"
}

/* COMMENTS */

MORE :
{
  <"/**" ~["/"]> { input_stream.backup(1); } : IN_FORMAL_COMMENT
|
  "/*" : IN_MULTI_LINE_COMMENT
}

SPECIAL_TOKEN :
{
  <SINGLE_LINE_COMMENT: "//" (~["\n", "\r"])* ("\n" | "\r" | "\r\n")?>
}

<IN_FORMAL_COMMENT>
SPECIAL_TOKEN :
{
  <FORMAL_COMMENT: "*/" > : DEFAULT
}

<IN_MULTI_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <MULTI_LINE_COMMENT: "*/" > : DEFAULT
}

<IN_FORMAL_COMMENT,IN_MULTI_LINE_COMMENT>
MORE :
{
  < ~[] >
}

/* RESERVED WORDS AND LITERALS */

TOKEN :
{
  < ABSTRACT: "abstract" >
| < ASSERT: "assert" >
| < BOOLEAN: "boolean" >
| < BREAK: "break" >
| < BYTE: "byte" >
| < CASE: "case" >
| < CATCH: "catch" >
| < CHAR: "char" >
| < CLASS: "class" >
| < CONST: "const" >
| < CONTINUE: "continue" >
| < _DEFAULT: "default" >
| < DO: "do" >
| < DOUBLE: "double" >
| < ELSE: "else" >
| < ENUM: "enum" >
| < EXTENDS: "extends" >
| < FALSE: "false" >
| < FINAL: "final" >
| < FINALLY: "finally" >
| < FLOAT: "float" >
| < FOR: "for" >
| < GOTO: "goto" >
| < IF: "if" >
| < IMPLEMENTS: "implements" >
| < IMPORT: "import" >
| < INSTANCEOF: "instanceof" >
| < INT: "int" >
| < INTERFACE: "interface" >
| < LONG: "long" >
| < NATIVE: "native" >
| < NEW: "new" >
| < NULL: "null" >
| < PACKAGE: "package">
| < PRIVATE: "private" >
| < PROTECTED: "protected" >
| < PUBLIC: "public" >
| < RETURN: "return" >
| < SHORT: "short" >
| < STATIC: "static" >
| < STRICTFP: "strictfp" >
| < SUPER: "super" >
| < SWITCH: "switch" >
| < SYNCHRONIZED: "synchronized" >
| < THIS: "this" >
| < THROW: "throw" >
| < THROWS: "throws" >
| < TRANSIENT: "transient" >
| < TRUE: "true" >
| < TRY: "try" >
| < VOID: "void" >
| < VOLATILE: "volatile" >
| < WHILE: "while" >
}

// Quadriga Tokens:

TOKEN :
{    < AT_REMOVE:    "@remove" >
  | < AT_ADD:       "@add" >
  | < AT_SYSTEM:    "@system" >
  | < AT_STRUCT:    "@struct" >
  | < AT_COMPONENT: "@component" >
  | < AT_PROTOTYPE: "@prototype" >
  | < AT_CONST:     "@const" >
  | < AT_COMPONENTS:      "@components" >
  | < AT_ADDITIONAL_INFO: "@additionalInfo" >
  | < AT_EXTERN_INFO:     "@externInfo" >
  | < AT_EVENT:           "@event" >
  | < AT_NEW_ENTITY:      "@newEntity" >
  | < AT_ERASE_ENTITY:    "@eraseEntity" >
  | < AT_CHANGE:   "@change" >
  | < AT_UPDATE:   "@update" >
  | < AT_QUADRIGA: "@quadriga" >
  | < AT_THREAD:   "@thread" >
  | < AT_INIT:     "@init" >
  | < AT_SYSTEMS:  "@systems" >
  | < AT_AFFECTED_SYSTEMS: "@affectedSystems" >
  | < AT_CHANGED: "@changed" >
  | < AT_DISCARD: "@discard" >
  | < AT_OLD:     "@old" >
  | < AT_CHILD:   "@child" >
  | < AT_JAVA:    "@java" >
  | < AT_MAIN:    "@main" >
  | < ENTITY:     "Entity" >

}   

/* LITERALS */

TOKEN :
{
  < INTEGER_LITERAL:
        <DECIMAL_LITERAL> (["l","L"])?
      | <HEX_LITERAL> (["l","L"])?
      | <OCTAL_LITERAL> (["l","L"])?
  >
|
  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* >
|
  < #HEX_LITERAL: "0" ["x","X"] (<HEXADECIMAL_DIGIT>)+ >
|
  < #OCTAL_LITERAL: "0" (["0"-"7"])* >
|
  < FLOATING_POINT_LITERAL:
        <DECIMAL_FLOATING_POINT_LITERAL>
      | <HEXADECIMAL_FLOATING_POINT_LITERAL>
  >
|
  < #DECIMAL_FLOATING_POINT_LITERAL:
        (["0"-"9"])+ "." (["0"-"9"])* (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | "." (["0"-"9"])+ (<DECIMAL_EXPONENT>)? (["f","F","d","D"])?
      | (["0"-"9"])+ <DECIMAL_EXPONENT> (["f","F","d","D"])?
      | (["0"-"9"])+ (<DECIMAL_EXPONENT>)? ["f","F","d","D"]
  >
|
  < #DECIMAL_EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ >
|
  < #HEXADECIMAL_FLOATING_POINT_LITERAL:
        "0" ["x", "X"] (<HEXADECIMAL_DIGIT>)+ (".")? <HEXADECIMAL_EXPONENT> (["f","F","d","D"])?
      | "0" ["x", "X"] (<HEXADECIMAL_DIGIT>)* "." (["0"-"9","a"-"f","A"-"F"])+ <HEXADECIMAL_EXPONENT> (["f","F","d","D"])?
  >
|
  < #HEXADECIMAL_EXPONENT: ["p","P"] (["+","-"])? (["0"-"9"])+ >
|
  < CHARACTER_LITERAL:
      "'"
      (   (~["'","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )
      "'"
  >
|
  < STRING_LITERAL:
      "\""
      (   (~["\"","\\","\n","\r"])
        | ("\\"
            ( ["n","t","b","r","f","\\","'","\""]
            | ["0"-"7"] ( ["0"-"7"] )?
            | ["0"-"3"] ["0"-"7"] ["0"-"7"]
            )
          )
      )*
      "\""
  >
| < #HEXADECIMAL_DIGIT : ["0"-"9","a"-"f","A"-"F"] >
}

/* IDENTIFIERS */

TOKEN :
{
  < IDENTIFIER: <LETTER> (<PART_LETTER>)* >
|
  < #LETTER:
      [  // all chars for which Character.isIdentifierStart is true
         "$",
         "A"-"Z",
         "_",
         "a"-"z",
         "\u00a2"-"\u00a5",
         "\u00aa",
         "\u00b5",
         "\u00ba",
         "\u00c0"-"\u00d6",
         "\u00d8"-"\u00f6",
         "\u00f8"-"\u021f",
         "\u0222"-"\u0233",
         "\u0250"-"\u02ad",
         "\u02b0"-"\u02b8",
         "\u02bb"-"\u02c1",
         "\u02d0"-"\u02d1",
         "\u02e0"-"\u02e4",
         "\u02ee",
         "\u037a",
         "\u0386",
         "\u0388"-"\u038a",
         "\u038c",
         "\u038e"-"\u03a1",
         "\u03a3"-"\u03ce",
         "\u03d0"-"\u03d7",
         "\u03da"-"\u03f3",
         "\u0400"-"\u0481",
         "\u048c"-"\u04c4",
         "\u04c7"-"\u04c8",
         "\u04cb"-"\u04cc",
         "\u04d0"-"\u04f5",
         "\u04f8"-"\u04f9",
         "\u0531"-"\u0556",
         "\u0559",
         "\u0561"-"\u0587",
         "\u05d0"-"\u05ea",
         "\u05f0"-"\u05f2",
         "\u0621"-"\u063a",
         "\u0640"-"\u064a",
         "\u0671"-"\u06d3",
         "\u06d5",
         "\u06e5"-"\u06e6",
         "\u06fa"-"\u06fc",
         "\u0710",
         "\u0712"-"\u072c",
         "\u0780"-"\u07a5",
         "\u0905"-"\u0939",
         "\u093d",
         "\u0950",
         "\u0958"-"\u0961",
         "\u0985"-"\u098c",
         "\u098f"-"\u0990",
         "\u0993"-"\u09a8",
         "\u09aa"-"\u09b0",
         "\u09b2",
         "\u09b6"-"\u09b9",
         "\u09dc"-"\u09dd",
         "\u09df"-"\u09e1",
         "\u09f0"-"\u09f3",
         "\u0a05"-"\u0a0a",
         "\u0a0f"-"\u0a10",
         "\u0a13"-"\u0a28",
         "\u0a2a"-"\u0a30",
         "\u0a32"-"\u0a33",
         "\u0a35"-"\u0a36",
         "\u0a38"-"\u0a39",
         "\u0a59"-"\u0a5c",
         "\u0a5e",
         "\u0a72"-"\u0a74",
         "\u0a85"-"\u0a8b",
         "\u0a8d",
         "\u0a8f"-"\u0a91",
         "\u0a93"-"\u0aa8",
         "\u0aaa"-"\u0ab0",
         "\u0ab2"-"\u0ab3",
         "\u0ab5"-"\u0ab9",
         "\u0abd",
         "\u0ad0",
         "\u0ae0",
         "\u0b05"-"\u0b0c",
         "\u0b0f"-"\u0b10",
         "\u0b13"-"\u0b28",
         "\u0b2a"-"\u0b30",
         "\u0b32"-"\u0b33",
         "\u0b36"-"\u0b39",
         "\u0b3d",
         "\u0b5c"-"\u0b5d",
         "\u0b5f"-"\u0b61",
         "\u0b85"-"\u0b8a",
         "\u0b8e"-"\u0b90",
         "\u0b92"-"\u0b95",
         "\u0b99"-"\u0b9a",
         "\u0b9c",
         "\u0b9e"-"\u0b9f",
         "\u0ba3"-"\u0ba4",
         "\u0ba8"-"\u0baa",
         "\u0bae"-"\u0bb5",
         "\u0bb7"-"\u0bb9",
         "\u0c05"-"\u0c0c",
         "\u0c0e"-"\u0c10",
         "\u0c12"-"\u0c28",
         "\u0c2a"-"\u0c33",
         "\u0c35"-"\u0c39",
         "\u0c60"-"\u0c61",
         "\u0c85"-"\u0c8c",
         "\u0c8e"-"\u0c90",
         "\u0c92"-"\u0ca8",
         "\u0caa"-"\u0cb3",
         "\u0cb5"-"\u0cb9",
         "\u0cde",
         "\u0ce0"-"\u0ce1",
         "\u0d05"-"\u0d0c",
         "\u0d0e"-"\u0d10",
         "\u0d12"-"\u0d28",
         "\u0d2a"-"\u0d39",
         "\u0d60"-"\u0d61",
         "\u0d85"-"\u0d96",
         "\u0d9a"-"\u0db1",
         "\u0db3"-"\u0dbb",
         "\u0dbd",
         "\u0dc0"-"\u0dc6",
         "\u0e01"-"\u0e30",
         "\u0e32"-"\u0e33",
         "\u0e3f"-"\u0e46",
         "\u0e81"-"\u0e82",
         "\u0e84",
         "\u0e87"-"\u0e88",
         "\u0e8a",
         "\u0e8d",
         "\u0e94"-"\u0e97",
         "\u0e99"-"\u0e9f",
         "\u0ea1"-"\u0ea3",
         "\u0ea5",
         "\u0ea7",
         "\u0eaa"-"\u0eab",
         "\u0ead"-"\u0eb0",
         "\u0eb2"-"\u0eb3",
         "\u0ebd",
         "\u0ec0"-"\u0ec4",
         "\u0ec6",
         "\u0edc"-"\u0edd",
         "\u0f00",
         "\u0f40"-"\u0f47",
         "\u0f49"-"\u0f6a",
         "\u0f88"-"\u0f8b",
         "\u1000"-"\u1021",
         "\u1023"-"\u1027",
         "\u1029"-"\u102a",
         "\u1050"-"\u1055",
         "\u10a0"-"\u10c5",
         "\u10d0"-"\u10f6",
         "\u1100"-"\u1159",
         "\u115f"-"\u11a2",
         "\u11a8"-"\u11f9",
         "\u1200"-"\u1206",
         "\u1208"-"\u1246",
         "\u1248",
         "\u124a"-"\u124d",
         "\u1250"-"\u1256",
         "\u1258",
         "\u125a"-"\u125d",
         "\u1260"-"\u1286",
         "\u1288",
         "\u128a"-"\u128d",
         "\u1290"-"\u12ae",
         "\u12b0",
         "\u12b2"-"\u12b5",
         "\u12b8"-"\u12be",
         "\u12c0",
         "\u12c2"-"\u12c5",
         "\u12c8"-"\u12ce",
         "\u12d0"-"\u12d6",
         "\u12d8"-"\u12ee",
         "\u12f0"-"\u130e",
         "\u1310",
         "\u1312"-"\u1315",
         "\u1318"-"\u131e",
         "\u1320"-"\u1346",
         "\u1348"-"\u135a",
         "\u13a0"-"\u13f4",
         "\u1401"-"\u166c",
         "\u166f"-"\u1676",
         "\u1681"-"\u169a",
         "\u16a0"-"\u16ea",
         "\u1780"-"\u17b3",
         "\u17db",
         "\u1820"-"\u1877",
         "\u1880"-"\u18a8",
         "\u1e00"-"\u1e9b",
         "\u1ea0"-"\u1ef9",
         "\u1f00"-"\u1f15",
         "\u1f18"-"\u1f1d",
         "\u1f20"-"\u1f45",
         "\u1f48"-"\u1f4d",
         "\u1f50"-"\u1f57",
         "\u1f59",
         "\u1f5b",
         "\u1f5d",
         "\u1f5f"-"\u1f7d",
         "\u1f80"-"\u1fb4",
         "\u1fb6"-"\u1fbc",
         "\u1fbe",
         "\u1fc2"-"\u1fc4",
         "\u1fc6"-"\u1fcc",
         "\u1fd0"-"\u1fd3",
         "\u1fd6"-"\u1fdb",
         "\u1fe0"-"\u1fec",
         "\u1ff2"-"\u1ff4",
         "\u1ff6"-"\u1ffc",
         "\u203f"-"\u2040",
         "\u207f",
         "\u20a0"-"\u20af",
         "\u2102",
         "\u2107",
         "\u210a"-"\u2113",
         "\u2115",
         "\u2119"-"\u211d",
         "\u2124",
         "\u2126",
         "\u2128",
         "\u212a"-"\u212d",
         "\u212f"-"\u2131",
         "\u2133"-"\u2139",
         "\u2160"-"\u2183",
         "\u3005"-"\u3007",
         "\u3021"-"\u3029",
         "\u3031"-"\u3035",
         "\u3038"-"\u303a",
         "\u3041"-"\u3094",
         "\u309d"-"\u309e",
         "\u30a1"-"\u30fe",
         "\u3105"-"\u312c",
         "\u3131"-"\u318e",
         "\u31a0"-"\u31b7",
         "\u3400"-"\u4db5",
         "\u4e00"-"\u9fa5",
         "\ua000"-"\ua48c",
         "\uac00"-"\ud7a3",
         "\uf900"-"\ufa2d",
         "\ufb00"-"\ufb06",
         "\ufb13"-"\ufb17",
         "\ufb1d",
         "\ufb1f"-"\ufb28",
         "\ufb2a"-"\ufb36",
         "\ufb38"-"\ufb3c",
         "\ufb3e",
         "\ufb40"-"\ufb41",
         "\ufb43"-"\ufb44",
         "\ufb46"-"\ufbb1",
         "\ufbd3"-"\ufd3d",
         "\ufd50"-"\ufd8f",
         "\ufd92"-"\ufdc7",
         "\ufdf0"-"\ufdfb",
         "\ufe33"-"\ufe34",
         "\ufe4d"-"\ufe4f",
         "\ufe69",
         "\ufe70"-"\ufe72",
         "\ufe74",
         "\ufe76"-"\ufefc",
         "\uff04",
         "\uff21"-"\uff3a",
         "\uff3f",
         "\uff41"-"\uff5a",
         "\uff65"-"\uffbe",
         "\uffc2"-"\uffc7",
         "\uffca"-"\uffcf",
         "\uffd2"-"\uffd7",
         "\uffda"-"\uffdc",
         "\uffe0"-"\uffe1",
         "\uffe5"-"\uffe6"
      ]
  >
|
  < #PART_LETTER:
      [  // all chars for which Character.isIdentifierPart is true
         "\u0000"-"\u0008",
         "\u000e"-"\u001b",
         "$",
         "0"-"9",
         "A"-"Z",
         "_",
         "a"-"z",
         "\u007f"-"\u009f",
         "\u00a2"-"\u00a5",
         "\u00aa",
         "\u00b5",
         "\u00ba",
         "\u00c0"-"\u00d6",
         "\u00d8"-"\u00f6",
         "\u00f8"-"\u021f",
         "\u0222"-"\u0233",
         "\u0250"-"\u02ad",
         "\u02b0"-"\u02b8",
         "\u02bb"-"\u02c1",
         "\u02d0"-"\u02d1",
         "\u02e0"-"\u02e4",
         "\u02ee",
         "\u0300"-"\u034e",
         "\u0360"-"\u0362",
         "\u037a",
         "\u0386",
         "\u0388"-"\u038a",
         "\u038c",
         "\u038e"-"\u03a1",
         "\u03a3"-"\u03ce",
         "\u03d0"-"\u03d7",
         "\u03da"-"\u03f3",
         "\u0400"-"\u0481",
         "\u0483"-"\u0486",
         "\u048c"-"\u04c4",
         "\u04c7"-"\u04c8",
         "\u04cb"-"\u04cc",
         "\u04d0"-"\u04f5",
         "\u04f8"-"\u04f9",
         "\u0531"-"\u0556",
         "\u0559",
         "\u0561"-"\u0587",
         "\u0591"-"\u05a1",
         "\u05a3"-"\u05b9",
         "\u05bb"-"\u05bd",
         "\u05bf",
         "\u05c1"-"\u05c2",
         "\u05c4",
         "\u05d0"-"\u05ea",
         "\u05f0"-"\u05f2",
         "\u0621"-"\u063a",
         "\u0640"-"\u0655",
         "\u0660"-"\u0669",
         "\u0670"-"\u06d3",
         "\u06d5"-"\u06dc",
         "\u06df"-"\u06e8",
         "\u06ea"-"\u06ed",
         "\u06f0"-"\u06fc",
         "\u070f"-"\u072c",
         "\u0730"-"\u074a",
         "\u0780"-"\u07b0",
         "\u0901"-"\u0903",
         "\u0905"-"\u0939",
         "\u093c"-"\u094d",
         "\u0950"-"\u0954",
         "\u0958"-"\u0963",
         "\u0966"-"\u096f",
         "\u0981"-"\u0983",
         "\u0985"-"\u098c",
         "\u098f"-"\u0990",
         "\u0993"-"\u09a8",
         "\u09aa"-"\u09b0",
         "\u09b2",
         "\u09b6"-"\u09b9",
         "\u09bc",
         "\u09be"-"\u09c4",
         "\u09c7"-"\u09c8",
         "\u09cb"-"\u09cd",
         "\u09d7",
         "\u09dc"-"\u09dd",
         "\u09df"-"\u09e3",
         "\u09e6"-"\u09f3",
         "\u0a02",
         "\u0a05"-"\u0a0a",
         "\u0a0f"-"\u0a10",
         "\u0a13"-"\u0a28",
         "\u0a2a"-"\u0a30",
         "\u0a32"-"\u0a33",
         "\u0a35"-"\u0a36",
         "\u0a38"-"\u0a39",
         "\u0a3c",
         "\u0a3e"-"\u0a42",
         "\u0a47"-"\u0a48",
         "\u0a4b"-"\u0a4d",
         "\u0a59"-"\u0a5c",
         "\u0a5e",
         "\u0a66"-"\u0a74",
         "\u0a81"-"\u0a83",
         "\u0a85"-"\u0a8b",
         "\u0a8d",
         "\u0a8f"-"\u0a91",
         "\u0a93"-"\u0aa8",
         "\u0aaa"-"\u0ab0",
         "\u0ab2"-"\u0ab3",
         "\u0ab5"-"\u0ab9",
         "\u0abc"-"\u0ac5",
         "\u0ac7"-"\u0ac9",
         "\u0acb"-"\u0acd",
         "\u0ad0",
         "\u0ae0",
         "\u0ae6"-"\u0aef",
         "\u0b01"-"\u0b03",
         "\u0b05"-"\u0b0c",
         "\u0b0f"-"\u0b10",
         "\u0b13"-"\u0b28",
         "\u0b2a"-"\u0b30",
         "\u0b32"-"\u0b33",
         "\u0b36"-"\u0b39",
         "\u0b3c"-"\u0b43",
         "\u0b47"-"\u0b48",
         "\u0b4b"-"\u0b4d",
         "\u0b56"-"\u0b57",
         "\u0b5c"-"\u0b5d",
         "\u0b5f"-"\u0b61",
         "\u0b66"-"\u0b6f",
         "\u0b82"-"\u0b83",
         "\u0b85"-"\u0b8a",
         "\u0b8e"-"\u0b90",
         "\u0b92"-"\u0b95",
         "\u0b99"-"\u0b9a",
         "\u0b9c",
         "\u0b9e"-"\u0b9f",
         "\u0ba3"-"\u0ba4",
         "\u0ba8"-"\u0baa",
         "\u0bae"-"\u0bb5",
         "\u0bb7"-"\u0bb9",
         "\u0bbe"-"\u0bc2",
         "\u0bc6"-"\u0bc8",
         "\u0bca"-"\u0bcd",
         "\u0bd7",
         "\u0be7"-"\u0bef",
         "\u0c01"-"\u0c03",
         "\u0c05"-"\u0c0c",
         "\u0c0e"-"\u0c10",
         "\u0c12"-"\u0c28",
         "\u0c2a"-"\u0c33",
         "\u0c35"-"\u0c39",
         "\u0c3e"-"\u0c44",
         "\u0c46"-"\u0c48",
         "\u0c4a"-"\u0c4d",
         "\u0c55"-"\u0c56",
         "\u0c60"-"\u0c61",
         "\u0c66"-"\u0c6f",
         "\u0c82"-"\u0c83",
         "\u0c85"-"\u0c8c",
         "\u0c8e"-"\u0c90",
         "\u0c92"-"\u0ca8",
         "\u0caa"-"\u0cb3",
         "\u0cb5"-"\u0cb9",
         "\u0cbe"-"\u0cc4",
         "\u0cc6"-"\u0cc8",
         "\u0cca"-"\u0ccd",
         "\u0cd5"-"\u0cd6",
         "\u0cde",
         "\u0ce0"-"\u0ce1",
         "\u0ce6"-"\u0cef",
         "\u0d02"-"\u0d03",
         "\u0d05"-"\u0d0c",
         "\u0d0e"-"\u0d10",
         "\u0d12"-"\u0d28",
         "\u0d2a"-"\u0d39",
         "\u0d3e"-"\u0d43",
         "\u0d46"-"\u0d48",
         "\u0d4a"-"\u0d4d",
         "\u0d57",
         "\u0d60"-"\u0d61",
         "\u0d66"-"\u0d6f",
         "\u0d82"-"\u0d83",
         "\u0d85"-"\u0d96",
         "\u0d9a"-"\u0db1",
         "\u0db3"-"\u0dbb",
         "\u0dbd",
         "\u0dc0"-"\u0dc6",
         "\u0dca",
         "\u0dcf"-"\u0dd4",
         "\u0dd6",
         "\u0dd8"-"\u0ddf",
         "\u0df2"-"\u0df3",
         "\u0e01"-"\u0e3a",
         "\u0e3f"-"\u0e4e",
         "\u0e50"-"\u0e59",
         "\u0e81"-"\u0e82",
         "\u0e84",
         "\u0e87"-"\u0e88",
         "\u0e8a",
         "\u0e8d",
         "\u0e94"-"\u0e97",
         "\u0e99"-"\u0e9f",
         "\u0ea1"-"\u0ea3",
         "\u0ea5",
         "\u0ea7",
         "\u0eaa"-"\u0eab",
         "\u0ead"-"\u0eb9",
         "\u0ebb"-"\u0ebd",
         "\u0ec0"-"\u0ec4",
         "\u0ec6",
         "\u0ec8"-"\u0ecd",
         "\u0ed0"-"\u0ed9",
         "\u0edc"-"\u0edd",
         "\u0f00",
         "\u0f18"-"\u0f19",
         "\u0f20"-"\u0f29",
         "\u0f35",
         "\u0f37",
         "\u0f39",
         "\u0f3e"-"\u0f47",
         "\u0f49"-"\u0f6a",
         "\u0f71"-"\u0f84",
         "\u0f86"-"\u0f8b",
         "\u0f90"-"\u0f97",
         "\u0f99"-"\u0fbc",
         "\u0fc6",
         "\u1000"-"\u1021",
         "\u1023"-"\u1027",
         "\u1029"-"\u102a",
         "\u102c"-"\u1032",
         "\u1036"-"\u1039",
         "\u1040"-"\u1049",
         "\u1050"-"\u1059",
         "\u10a0"-"\u10c5",
         "\u10d0"-"\u10f6",
         "\u1100"-"\u1159",
         "\u115f"-"\u11a2",
         "\u11a8"-"\u11f9",
         "\u1200"-"\u1206",
         "\u1208"-"\u1246",
         "\u1248",
         "\u124a"-"\u124d",
         "\u1250"-"\u1256",
         "\u1258",
         "\u125a"-"\u125d",
         "\u1260"-"\u1286",
         "\u1288",
         "\u128a"-"\u128d",
         "\u1290"-"\u12ae",
         "\u12b0",
         "\u12b2"-"\u12b5",
         "\u12b8"-"\u12be",
         "\u12c0",
         "\u12c2"-"\u12c5",
         "\u12c8"-"\u12ce",
         "\u12d0"-"\u12d6",
         "\u12d8"-"\u12ee",
         "\u12f0"-"\u130e",
         "\u1310",
         "\u1312"-"\u1315",
         "\u1318"-"\u131e",
         "\u1320"-"\u1346",
         "\u1348"-"\u135a",
         "\u1369"-"\u1371",
         "\u13a0"-"\u13f4",
         "\u1401"-"\u166c",
         "\u166f"-"\u1676",
         "\u1681"-"\u169a",
         "\u16a0"-"\u16ea",
         "\u1780"-"\u17d3",
         "\u17db",
         "\u17e0"-"\u17e9",
         "\u180b"-"\u180e",
         "\u1810"-"\u1819",
         "\u1820"-"\u1877",
         "\u1880"-"\u18a9",
         "\u1e00"-"\u1e9b",
         "\u1ea0"-"\u1ef9",
         "\u1f00"-"\u1f15",
         "\u1f18"-"\u1f1d",
         "\u1f20"-"\u1f45",
         "\u1f48"-"\u1f4d",
         "\u1f50"-"\u1f57",
         "\u1f59",
         "\u1f5b",
         "\u1f5d",
         "\u1f5f"-"\u1f7d",
         "\u1f80"-"\u1fb4",
         "\u1fb6"-"\u1fbc",
         "\u1fbe",
         "\u1fc2"-"\u1fc4",
         "\u1fc6"-"\u1fcc",
         "\u1fd0"-"\u1fd3",
         "\u1fd6"-"\u1fdb",
         "\u1fe0"-"\u1fec",
         "\u1ff2"-"\u1ff4",
         "\u1ff6"-"\u1ffc",
         "\u200c"-"\u200f",
         "\u202a"-"\u202e",
         "\u203f"-"\u2040",
         "\u206a"-"\u206f",
         "\u207f",
         "\u20a0"-"\u20af",
         "\u20d0"-"\u20dc",
         "\u20e1",
         "\u2102",
         "\u2107",
         "\u210a"-"\u2113",
         "\u2115",
         "\u2119"-"\u211d",
         "\u2124",
         "\u2126",
         "\u2128",
         "\u212a"-"\u212d",
         "\u212f"-"\u2131",
         "\u2133"-"\u2139",
         "\u2160"-"\u2183",
         "\u3005"-"\u3007",
         "\u3021"-"\u302f",
         "\u3031"-"\u3035",
         "\u3038"-"\u303a",
         "\u3041"-"\u3094",
         "\u3099"-"\u309a",
         "\u309d"-"\u309e",
         "\u30a1"-"\u30fe",
         "\u3105"-"\u312c",
         "\u3131"-"\u318e",
         "\u31a0"-"\u31b7",
         "\u3400"-"\u4db5",
         "\u4e00"-"\u9fa5",
         "\ua000"-"\ua48c",
         "\uac00"-"\ud7a3",
         "\uf900"-"\ufa2d",
         "\ufb00"-"\ufb06",
         "\ufb13"-"\ufb17",
         "\ufb1d"-"\ufb28",
         "\ufb2a"-"\ufb36",
         "\ufb38"-"\ufb3c",
         "\ufb3e",
         "\ufb40"-"\ufb41",
         "\ufb43"-"\ufb44",
         "\ufb46"-"\ufbb1",
         "\ufbd3"-"\ufd3d",
         "\ufd50"-"\ufd8f",
         "\ufd92"-"\ufdc7",
         "\ufdf0"-"\ufdfb",
         "\ufe20"-"\ufe23",
         "\ufe33"-"\ufe34",
         "\ufe4d"-"\ufe4f",
         "\ufe69",
         "\ufe70"-"\ufe72",
         "\ufe74",
         "\ufe76"-"\ufefc",
         "\ufeff",
         "\uff04",
         "\uff10"-"\uff19",
         "\uff21"-"\uff3a",
         "\uff3f",
         "\uff41"-"\uff5a",
         "\uff65"-"\uffbe",
         "\uffc2"-"\uffc7",
         "\uffca"-"\uffcf",
         "\uffd2"-"\uffd7",
         "\uffda"-"\uffdc",
         "\uffe0"-"\uffe1",
         "\uffe5"-"\uffe6",
         "\ufff9"-"\ufffb"
      ]
  >
}

/* SEPARATORS */

TOKEN :
{
  < LPAREN: "(" >
| < RPAREN: ")" >
| < LBRACE: "{" >
| < RBRACE: "}" >
| < LBRACKET: "[" >
| < RBRACKET: "]" >
| < SEMICOLON: ";" >
| < COMMA: "," >
| < DOT: "." >
| < AT: "@" >
}

/* OPERATORS */

TOKEN :
{
  < ASSIGN: "=" >
| < LT: "<" >
| < BANG: "!" >
| < TILDE: "~" >
| < HOOK: "?" >
| < COLON: ":" >
| < EQ: "==" >
| < LE: "<=" >
| < GE: ">=" >
| < NE: "!=" >
| < SC_OR: "||" >
| < SC_AND: "&&" >
| < INCR: "++" >
| < DECR: "--" >
| < PLUS: "+" >
| < MINUS: "-" >
| < STAR: "*" >
| < SLASH: "/" >
| < BIT_AND: "&" >
| < BIT_OR: "|" >
| < XOR: "^" >
| < REM: "%" >
| < LSHIFT: "<<" >
| < PLUSASSIGN: "+=" >
| < MINUSASSIGN: "-=" >
| < STARASSIGN: "*=" >
| < SLASHASSIGN: "/=" >
| < ANDASSIGN: "&=" >
| < ORASSIGN: "|=" >
| < XORASSIGN: "^=" >
| < REMASSIGN: "%=" >
| < LSHIFTASSIGN: "<<=" >
| < RSIGNEDSHIFTASSIGN: ">>=" >
| < RUNSIGNEDSHIFTASSIGN: ">>>=" >
| < ELLIPSIS: "..." >
}

/* >'s need special attention due to generics syntax. */
TOKEN :
{
  < RUNSIGNEDSHIFT: ">>>" >
  {
     matchedToken.kind = GT;
     ((cat.quadriga.parsers.tokens.MySimpleToken)matchedToken).realKind = RUNSIGNEDSHIFT;
     input_stream.backup(2);
     matchedToken.image = ">";
  }
| < RSIGNEDSHIFT: ">>" >
  {
     matchedToken.kind = GT;
     ((cat.quadriga.parsers.tokens.MySimpleToken)matchedToken).realKind = RSIGNEDSHIFT;
     input_stream.backup(1);
     matchedToken.image = ">";
  }
| < GT: ">" >
}


/*****************************************
 * THE JAVA LANGUAGE GRAMMAR STARTS HERE *
 *****************************************/

/*
 * Program structuring syntax follows.
 */

List<PrintInfo> CompilationUnit():
{
  List<PrintInfo> out = new LinkedList<PrintInfo>();
}
{
  [LOOKAHEAD( ( Annotation() )* "package" ) PackageDeclaration(out)
    {
      out.add(PrintIntro.getInstance());
    }
  ]
  ( ImportDeclaration(out) )*
  ( 
    {
      out.add(PrintIntro.getInstance());
    }
    TypeDeclaration(out)
  )+
  ( < "\u001a" > )?
  ( <STUFF_TO_IGNORE: ~[]> )?
  <EOF>
  {
    return out;
  }
}

void PackageDeclaration(List<PrintInfo> out):
{
  List<Token > tokens;
}
{
  Modifiers(out) "package" tokens = Name() ";"
  {
    String aux = tokens.get(0).image;
    for(int i = 1; i < tokens.size(); i++) {
      aux += "." + tokens.get(i).image;    }

    symbolTable.addPackage(aux);

    out.add(new PrintString("package " + aux + ";"));
  }
}

void ImportDeclaration(List<PrintInfo> out):
{
  boolean stat = false;
  List<Token> tokens;
  String aux;
}
{
  "import"
  [ "static"
    {
      stat = true;
    }
  ]
  tokens = Name()
  {
    aux = tokens.get(0).image;
    for(int i = 1; i < tokens.size(); i++) {
      aux += "." + tokens.get(i).image;
    }  }
  (     "." "*"
    {
      symbolTable.addPackage(aux);

      aux += ".*";
    }
  |    {
      try {
        Class<?> clazz = Class.forName(aux);
        BaseSymbol symbol = new TypeSymbol(ClassOrInterfaceTypeRef.getFromClass(clazz));
        symbolTable.addGlobalSymbol(symbol);
      } catch (ClassNotFoundException e) {
        //TODO revisar això
        BaseSymbol symbol = new TypeSymbol(UnknownType.empty);
        symbolTable.addGlobalSymbol(symbol);
      }    }
  )
  ";"
  {
    out.add(new PrintString("import " + aux + ";"));
  }
}

/*
 * Modifiers. We match all modifiers in a single rule to reduce the chances of
 * syntax errors for simple modifier mistakes. It will also enable us to give
 * better error messages.
 */

int Modifiers(List<PrintInfo> out):
{
   int modifiers = 0;
}
{
 (
  LOOKAHEAD(2)
  (
   "public"
   {
     modifiers |= ModifierSet.PUBLIC;
     out.add(new PrintString("public"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "static"
   {
     modifiers |= ModifierSet.STATIC;
     out.add(new PrintString("static"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "protected"
   {
     modifiers |= ModifierSet.PROTECTED;
     out.add(new PrintString("protected"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "private"
   {
     modifiers |= ModifierSet.PRIVATE;
     out.add(new PrintString("private"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "final"
   {
     modifiers |= ModifierSet.FINAL;
     out.add(new PrintString("final"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "abstract"
   {
     modifiers |= ModifierSet.ABSTRACT;
     out.add(new PrintString("abstract"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "synchronized"
   {
     modifiers |= ModifierSet.SYNCHRONIZED;
     out.add(new PrintString("synchronized"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "native"
   {
     modifiers |= ModifierSet.NATIVE;
     out.add(new PrintString("native"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "transient"
   {
     modifiers |= ModifierSet.TRANSIENT;
     out.add(new PrintString("transient"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "volatile"
   {
     modifiers |= ModifierSet.VOLATILE;
     out.add(new PrintString("volatile"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   "strictfp"
   {
     modifiers |= ModifierSet.STRICTFP;
     out.add(new PrintString("strictfp"));
     out.add(PrintWhiteSpace.getInstance());
   }
  |
   Annotation(out)
  )
 )*

 {
    return modifiers;
 }
}

/*
 * Declaration syntax follows.
 */
void TypeDeclaration(List<PrintInfo> out):
{
   int modifiers;
}
{
  (
    ";"
    {
      out.add(new PrintString(";"));
      out.add(PrintIntro.getInstance());
    }
  |
    modifiers = Modifiers(out)
    (
      ClassOrInterfaceDeclaration(modifiers, out)
    |
      EnumDeclaration(modifiers, out)
    |
      AnnotationTypeDeclaration(modifiers, out)
    )
  )
}


void ClassOrInterfaceDeclaration(int modifiers, List<PrintInfo> out):
{
   boolean isInterface = false;
   Token t;
}
{
  ( "class" | "interface" { isInterface = true; } )
  t=<IDENTIFIER>
  {
    out.add(new PrintString(isInterface?"interface":"class"));
    out.add(PrintWhiteSpace.getInstance());
    out.add(new PrintString(t.image));
  }
  [ TypeParameters(out) ]
  {
    out.add(PrintWhiteSpace.getInstance());
  }
  [ ExtendsList(isInterface, out) ]
  [ ImplementsList(isInterface, out) ]
  ClassOrInterfaceBody(isInterface, out)
}

void ExtendsList(boolean isInterface, List<PrintInfo> out):
{
   boolean extendsMoreThanOne = false;
}
{
   "extends"
   {
     out.add(new PrintString("extends"));
     out.add(PrintWhiteSpace.getInstance());
   }
   ClassOrInterfaceType()
   ( "," 
     {
       out.add(new PrintString(","));
       out.add(PrintWhiteSpace.getInstance());
     }
     ClassOrInterfaceType() { extendsMoreThanOne = true; }
   )*
   {
      if (extendsMoreThanOne && !isInterface)
         throw new ParseException("A class cannot extend more than one other class");
   }
}

void ImplementsList(boolean isInterface, List<PrintInfo> out):
{}
{
   "implements"
   {
     out.add(new PrintString("implements"));
     out.add(PrintWhiteSpace.getInstance());
   }
   ClassOrInterfaceType()
   ( "," 
     {
       out.add(new PrintString(","));
       out.add(PrintWhiteSpace.getInstance());
     }
     ClassOrInterfaceType()
   )*
   {
      if (isInterface)
         throw new ParseException("An interface cannot implement other interfaces");
   }
}

void EnumDeclaration(int modifiers, List<PrintInfo> out):
{
  Token t;
}
{
  "enum" t=<IDENTIFIER>
  {
    out.add(new PrintString("enum"));
    out.add(PrintWhiteSpace.getInstance());
    out.add(new PrintString(t.image));
  }
  [ ImplementsList(false, out) 
    {
      out.add(PrintWhiteSpace.getInstance());
    }
  ]
  EnumBody(out)
}

void EnumBody(List<PrintInfo> out):
{}
{
   "{"
   {
    out.add(new PrintString("{"));
    out.add(PrintInitTab.getInstance());
    out.add(PrintIntro.getInstance());
   }
   [ EnumConstant(out)
     ( LOOKAHEAD(2) ","
       {
         out.add(new PrintString(","));
         out.add(PrintWhiteSpace.getInstance());
       }
       EnumConstant(out)
     )*
   ]
    [ "," ]
   [ ";"
     ( 
     {
       out.add(PrintIntro.getInstance());
     }
     ClassOrInterfaceBodyDeclaration(false, out) )*
   ]
   "}"
   {
     out.add(PrintEndTab.getInstance());
     out.add(PrintIntro.getInstance());
     out.add(new PrintString("}"));
   }
}

void EnumConstant(List<PrintInfo> out):
{
  Token t;
}
{
  Modifiers(out) t=<IDENTIFIER>
  {
    out.add(new PrintString(t.image));
  }
  [ Arguments() ]
  [ ClassOrInterfaceBody(false, out) ]
}

void TypeParameters(List<PrintInfo> out):
{}
{
   "<"
   {
     out.add(new PrintString("<"));
   }
   TypeParameter(out)
   ( ","
   {
     out.add(new PrintString(","));
     out.add(PrintWhiteSpace.getInstance());
   }
   TypeParameter(out)
   )*
   ">"
   {
     out.add(new PrintString(">"));
   }
}

void TypeParameter(List<PrintInfo> out):
{
  Token t;
}
{
   t=<IDENTIFIER>
   {
     out.add(new PrintString(t.image));
   }
   [
     {
       out.add(PrintWhiteSpace.getInstance());
     }
     TypeBound(out)
   ]
}

void TypeBound(List<PrintInfo> out):
{}
{
   "extends"
   {
     out.add(new PrintString("extends"));
     out.add(PrintWhiteSpace.getInstance());
   }
   ClassOrInterfaceType()
   ( "&"
     {
       out.add(PrintWhiteSpace.getInstance());
       out.add(new PrintString("&"));
       out.add(PrintWhiteSpace.getInstance());
     }
     ClassOrInterfaceType()
   )*
}

void ClassOrInterfaceBody(boolean isInterface, List<PrintInfo> out):
{
}
{
  "{"
  {
    out.add(new PrintString("{"));
    out.add(PrintInitTab.getInstance());
    out.add(PrintIntro.getInstance());
  }
  ( ClassOrInterfaceBodyDeclaration(isInterface, out)
    {
      out.add(PrintIntro.getInstance());
    }
  )*
  "}"
  {
    out.add(PrintEndTab.getInstance());
    out.add(PrintIntro.getInstance());
    out.add(new PrintString("}"));
    out.add(PrintIntro.getInstance());
  }
}

void ClassOrInterfaceBodyDeclaration(boolean isInterface, List<PrintInfo> out):
{
  //TODO
  boolean isNestedInterface = false;
  int modifiers;
}
{
  (
    LOOKAHEAD(2)
    Initializer(out)
    {
       if (isInterface)
          throw new ParseException("An interface cannot have initializers");
    }
  |
    modifiers = Modifiers(out) // Just get all the modifiers out of the way. If you want to do
                // more checks, pass the modifiers down to the member
    (
        ClassOrInterfaceDeclaration(modifiers, out)
      |
        EnumDeclaration(modifiers, out)
      |
        LOOKAHEAD( [ TypeParameters() ] <IDENTIFIER> "(" )
        ConstructorDeclaration(out)
      |
        LOOKAHEAD( Type() <IDENTIFIER> ( "[" "]" )* ( "," | "=" | ";" ) )
        FieldDeclaration(modifiers, out)
      |
        MethodDeclaration(modifiers, out)
      |
        AnnotationTypeDeclaration(modifiers, out)
    )
  |
    ";"
  )
}

void FieldDeclaration(int modifiers, List<PrintInfo> out):
{
  VarAndInit v;
  BaseType tipus;
}
{
  // Modifiers are already matched in the caller
  tipus = Type()
  {
    out.add(PrintWhiteSpace.getInstance());
  }
  v = VariableDeclarator(modifiers, tipus)
  ( ","
    {
      //TODO
    }
    v = VariableDeclarator(modifiers, tipus)
  )* ";"
  {
    out.add(new PrintString(";"));
  }
}

VarAndInit VariableDeclarator(int modifiers, BaseType type):
{
  VarAndInit vai;
  ExpressionNode initialization;
  ExpressionNode leftHand;
}
{
  vai = VariableDeclaratorId(type)
  {
    vai.modifiers = modifiers;
    if(localBlock != null) //Local var
    {
      LocalVariableSymbol localVar = new LocalVariableSymbol(modifiers, vai.type, vai.name.image);
      symbolTable.addSymbol(localVar);
      localBlock.addLocalVariable(localVar);

      leftHand = new LocalVarAccess(localVar, new CodeZoneClass(vai.name,file));
    } else {
      //Field
      leftHand = new ProxyDataAccess("Proxy field: " + vai.name, new CodeZoneClass(vai.name,file));    }  }
  [ "="
    initialization = VariableInitializer(type)
    {
      vai.init = new AssigmentStatementNode(
                                      AssigmentStatementNode.Operator.ASSIGN,
                                      leftHand,
                                      initialization);    }
  ]
  {    return vai;
  }
}

VarAndInit VariableDeclaratorId(BaseType type):
{
  Token t;
  VarAndInit vai = new VarAndInit();
}
{
  t=<IDENTIFIER>
  {
    vai.name = t;
    vai.type = type;
  }
  ( "[" "]" 
    {
      vai.type = new ArrayType(vai.type);
    }
  )*
  {
    return vai;  }
}

ExpressionNode VariableInitializer(BaseType base):
{
  ExpressionNode result;
}
{
  (
    result = ArrayInitializer(base)
  |
    result = Expression()
  )
  {    return result;
  }
}

ExpressionNode ArrayInitializer(BaseType base):
{
  ExpressionNode aux;
  List<ExpressionNode> listOfInits = new LinkedList<ExpressionNode>();
  Token t, t2;
  if(base instanceof ArrayType) {
    base = ((ArrayType)base).base;  }
}
{
  t="{"
  [ aux = VariableInitializer(base)
    {
      listOfInits.add(aux);
    }
    ( LOOKAHEAD(2) "," aux = VariableInitializer(base)
      {
        listOfInits.add(aux);
      }
    )*
  ]
  [ "," ]
  t2="}"
  {
    ExpressionNode[] arraySize = {new LiteralData.IntegerLiteral(listOfInits.size())};

    ArrayAllocationExpressionNode allocation = new ArrayAllocationExpressionNode(
                                                   base,
                                                   arraySize,
                                                   1,
                                                   new CodeZoneClass(t, t2,file)
                                                   ); 
    return new ArrayInitializerNode(allocation,
                                    listOfInits.toArray(
                                          new ExpressionNode[listOfInits.size()])
                                    );
  }
}

void MethodDeclaration(int modifiers, List<PrintInfo> out):
{
  BlockCode bc;
  List<PrintInfo> other = new LinkedList<PrintInfo>();

  symbolTable.newContext();
  symbolTable.addSymbol(new ThisSymbol());
}
{
  // Modifiers already matched in the caller!
  [ TypeParameters(out) ]
  {
    out.add(PrintWhiteSpace.getInstance());
  }
  ResultType()
  {
    out.add(PrintWhiteSpace.getInstance());
  }
  MethodDeclarator(out)
  [ "throws"
    {
      out.add(PrintWhiteSpace.getInstance());
      out.add(new PrintString("throws"));
      out.add(PrintWhiteSpace.getInstance());
    }
    NameList()
  ]
  ( bc = Block()
    {
      String treeString = bc.treeStringRepresentation();
      out.addAll( MegaPrinter.getInstance().format(treeString) );
    }
  | ";"
    {
      out.add(new PrintString(";"));
    }
  )
  {
    symbolTable.deleteContext();  }
}

void MethodDeclarator(List<PrintInfo> out):
{
  Token t;
  List<ParameterClass> params;
}
{
  t=<IDENTIFIER>
  {
    out.add(new PrintString(t.image));
  }
  /* Això servia en el Java vell
  ( "[" "]"
    {
      out.add(new PrintString("["));
      out.add(new PrintString("]"));
    }
  )*
  */
  params = FormalParameters()
  {
    for(ParameterClass param : params)
    {
      symbolTable.addSymbol(new LocalVariableSymbol(param.modifiers,
                                                    param.type,
                                                    param.name));
    }
  }
  {
    out.add(PrintIntro.getInstance());
    out.add(new PrintString("Params"));
    for(ParameterClass param : params)
    {
      out.add(PrintIntro.getInstance());
      out.add(new PrintString(param.name + ": " + param.type));
    }
    out.add(PrintIntro.getInstance());
  }
}

List<ParameterClass> FormalParameters():
{
  List<ParameterClass> params = new LinkedList<ParameterClass>();
  ParameterClass param;
}
{
  "("
  [ param = FormalParameter()
    {
      params.add(param);    }
    ( ","
    param = FormalParameter()
    {
      params.add(param);
    }
    )*
  ]
  ")"
  {
    return params;
  }
}

ParameterClass FormalParameter():
{
  int modifiers;
  BaseType type;
  List<PrintInfo> out = new LinkedList<PrintInfo>();
  VarAndInit vai;
  ExpressionNode init = null;
  boolean varargs = false;
  Token t;
  String semantic = null;
}
{
  // danson, added
  //          [ "final" | Annotation() ]
  // See Java Language Specification, 3rd Edition, section 8.4.1
  modifiers = Modifiers(out)
  [ "final"
    {
      modifiers &= FINAL;
    }
  | Annotation(out)
    {      //caca
    }
    
  ]
  type = Type()
  [ "..."
  {
    type = new ArrayType(type);
    varargs = true;
  }
  ]
  vai = VariableDeclaratorId(type)

  //La semàntica fa que quadriga hi posi el paràmetre. Per tant no es pot posar
  //per defecte
  [ "=" init = Expression() 
  | ":" t = < IDENTIFIER > { semantic = t.image; } ]
  {
    return new ParameterClass(
      new CodeZoneClass(vai.name,file),
      vai.type,
      vai.name.image,
      varargs,
      modifiers,
      init,
      semantic);  }
}

void ConstructorDeclaration(List<PrintInfo> out):
{
  Token t;
  out.add(PrintWhiteSpace.getInstance());
  StatementNode bsn;

  List<ParameterClass > params;

  symbolTable.newContext();
  symbolTable.addSymbol(new ThisSymbol());
}
{
  [ TypeParameters(out) ]
  // Modifiers matched in the caller
  t=<IDENTIFIER>
  {
    out.add(new PrintString(t.image));
  }
  params = FormalParameters()
  {
    for(ParameterClass param : params)
    {
      symbolTable.addSymbol(new LocalVariableSymbol(param.modifiers,
                                                    param.type,
                                                    param.name));
    }
  }
  {
    out.add(PrintIntro.getInstance());
    out.add(new PrintString("Params"));
    for(ParameterClass param : params)
    {
      out.add(PrintIntro.getInstance());
      out.add(new PrintString(param.name + ": " + param.type));    }
    out.add(PrintIntro.getInstance());  }
  [ "throws"
    {
      out.add(PrintWhiteSpace.getInstance());
      out.add(new PrintString("throws"));
      out.add(PrintWhiteSpace.getInstance());
    }
  NameList()
  ]
  "{"
  {
    out.add(PrintWhiteSpace.getInstance());
    out.add(new PrintString("{"));
    out.add(PrintInitTab.getInstance());
    out.add(PrintIntro.getInstance());
  } 
  [ LOOKAHEAD(ExplicitConstructorInvocation())
       ExplicitConstructorInvocation(out)
  ]
  ( bsn = BlockStatement()
    {
      String treeString = bsn.treeStringRepresentation();
      out.addAll( MegaPrinter.getInstance().format(treeString) );
    }
  )*
  "}"
  {
    while(out.get(out.size()-1) == PrintIntro.getInstance())
      out.remove(out.size()-1);
    if(out.get(out.size()-1) != PrintInitTab.getInstance()) {
      out.add(PrintEndTab.getInstance());
      out.add(PrintIntro.getInstance());
    } else {
      out.add(PrintEndTab.getInstance());
    }
    out.add(new PrintString("}"));
  }

  {
    symbolTable.deleteContext();  }
}

void ExplicitConstructorInvocation(List<PrintInfo> out):
{
  Token t;
}
{
  ( t=<IDENTIFIER> "."
    {
      out.add(new PrintString(t.image));
      out.add(new PrintString("."));
    }
  )*
  [ LOOKAHEAD(2) "this" "."
    {
      out.add(new PrintString("this"));
      out.add(new PrintString("."));
    }
  ]
  [ TypeArguments() ]
  ( "this"
    {
      out.add(new PrintString("this"));
    }
  | "super"
    {
      out.add(new PrintString("super"));
    }
  ) Arguments() ";"
    {
      out.add(new PrintString(";"));
      out.add(PrintIntro.getInstance());
    }
}

void Initializer(List<PrintInfo> out):
{}
{
  [ "static"
  {
    {
      out.add(new PrintString("static"));
      out.add(PrintWhiteSpace.getInstance());
    }
  }
  ] Block() //TODO
}


/*
 * Type, name and expression syntax follows.
 */

BaseType Type():
{
  BaseType t;
}
{
  (
    t=QuadrigaEntity()
  | 
    LOOKAHEAD(2) t = ReferenceType()
  |
    t = PrimitiveType()
  )
  {
    return t;
  }
}

BaseType ReferenceType():
{
  BaseType type;
}
{
  (
    
    type = PrimitiveType()
    ( LOOKAHEAD(2) "[" "]"
      {
        type = new ArrayType(type);
      }
    )+
  |
    type = ClassOrInterfaceType() 
    ( LOOKAHEAD(2) "[" "]"
      {
        type = new ArrayType(type);
      }
    )*
  )
  {    return type;
  }
}

BaseType ClassOrInterfaceType():
{
  Token t, first, last;
  List<String> aux = new LinkedList<String>();
  List<ParametrizedClass.ParameterClass> arguments = null;
  List<PrintInfo> out = new LinkedList<PrintInfo>();
  BaseType type;
}
{
  t=<IDENTIFIER>
  {
    aux.add(t.image);
    first = last = t;
  }
  (     LOOKAHEAD(2)arguments = TypeArguments()
  |
   {
     arguments = null;   }
  )
  ( LOOKAHEAD(2) "." t=<IDENTIFIER>
    {
      aux.add(t.image);
      last = t;
    }
    [ LOOKAHEAD(2) arguments = TypeArguments()
      //TODO reformular tot això
    ]
  )*
  {
    CodeZone cz = new CodeZoneClass(first, last, file);
    String name = aux.get(0);
    for(int i = 1; i < aux.size(); i++) {
	  name += "." + aux.get(i);    }
    BaseSymbol symbol = symbolTable.findSymbol(name);
    BaseType result = null;
    if(symbol != null) {
      if(symbol instanceof TypeSymbol) {
        result = ((TypeSymbol)symbol).type;      } else {
        errorLog.insertError("El simbol \"" + name + "\" no és un tipus.", cz);
        return UnknownType.empty;       }    } else {
      errorLog.insertWarning("No s'ha trobat la classe \"" + name + "\".", cz);
      return new UnknownType(name);    }

    //Type Arguments
    if(arguments != null) {
      if(result instanceof ClassOrInterfaceTypeRef) {
        result = new ParametrizedClass((ClassOrInterfaceTypeRef)result, arguments);
      } else {
        result = new ParametrizedClass(result, arguments);      }    }
    return result;  }
}

List<ParametrizedClass.ParameterClass> TypeArguments():
{
  List<ParametrizedClass.ParameterClass> arguments = new LinkedList<ParametrizedClass.ParameterClass>();
  ParametrizedClass.ParameterClass argument;
}
{
   "<"
   argument = TypeArgument()
   {
     arguments.add(argument);   }
   ( ","
     argument = TypeArgument()
     {
       arguments.add(argument);
     }
   )* ">"
   {
     return arguments;
   }
}

ParametrizedClass.ParameterClass TypeArgument():
{
  ParametrizedClass.ParameterClass typeArgument;
  BaseType base;
}
{
 ( 
   base = ReferenceType()
   {
     typeArgument = new ParametrizedClass.ParameterClass(base);   }
 |
   "?"
   (
     typeArgument = WildcardBounds()
   |
     {
       typeArgument = new ParametrizedClass.ParameterClass();     }
   )
 )
 {   return typeArgument;
 }
}

ParametrizedClass.ParameterClass WildcardBounds():
{
  List<PrintInfo> out = new LinkedList<PrintInfo>();
  ParametrizedClass.ParameterClass typeArgument;
  BaseType base;
}
{
 (
   "extends" base=ReferenceType()
   {
     typeArgument = new ParametrizedClass.ParameterClass(base,ParametrizedClass.ParameterClass.Bound.EXTENDS);
   }
 |
   "super" base=ReferenceType()
   {
     typeArgument = new ParametrizedClass.ParameterClass(base,ParametrizedClass.ParameterClass.Bound.SUPER);
   }
 )
 {
   return typeArgument;
 }
}


PrimitiveTypeRef PrimitiveType():
{
  Token t;
}
{
  (
      t="boolean"
    |
      t="char"
    |
      t="byte"
    |
      t="short"
    |
      t="int"
    |
      t="long"
    |
      t="float"
    |
      t="double"
  )
  {
    return PrimitiveTypeRef.getFromName(t.image);
  }
}

BaseType ResultType():
{
  BaseType type;
  Token t;
}
{
  (   
      t="void"
      {
        type = PrimitiveTypeRef.getFromName(t.image);
      }
    |
      type = Type()
    )
    {      return type;
    }
}

List<Token> Name():
/*
 * A lookahead of 2 is required below since "Name" can be followed
 * by a ".*" when used in the context of an "ImportDeclaration".
 */
{
  List<Token> tokens = new LinkedList<Token>();
  Token t;
}
{
  t=<IDENTIFIER>
  {
    tokens.add(t);
  }
  ( LOOKAHEAD(2) "." t=<IDENTIFIER>
    {
      tokens.add(t);
    }
  )*
  {    return tokens;
  }
}

List<List<Token>> NameList():
{
  List<Token> aux;
  List<List<Token>> names = new LinkedList<List<Token>>();
}
{
  aux = Name()
  {
    names.add(aux);  }
  ( ","
    Name()
    {      names.add(aux);
    }
  )*
  {    return names;
  }
}


/*
 * Expression syntax follows.
 */

ExpressionNode Expression():
/*
 * This expansion has been written this way instead of:
 *   Assignment() | ConditionalExpression()
 * for performance reasons.
 * However, it is a weakening of the grammar for it allows the LHS of
 * assignments to be any conditional expression whereas it can only be
 * a primary expression.  Consider adding a semantic predicate to work
 * around this.
 */
{
  ExpressionNode finalNode, auxNode;
  AssigmentStatementNode.Operator operator; 
}
{
  finalNode = ConditionalExpression()
  [
    LOOKAHEAD(2)
    operator = AssignmentOperator()
    auxNode = Expression()
    {
      finalNode = new AssigmentExpressionNode(operator, finalNode, auxNode);    }
  ]

  {    return finalNode;
  }
}

AssigmentStatementNode.Operator AssignmentOperator():
{
  AssigmentStatementNode.Operator op;
}
{
  ( "="    { op = AssigmentStatementNode.Operator.ASSIGN; }
  | "*="   { op = AssigmentStatementNode.Operator.STARASSIGN; }
  | "/="   { op = AssigmentStatementNode.Operator.SLASHASSIGN; }
  | "%="   { op = AssigmentStatementNode.Operator.REMASSIGN; }
  | "+="   { op = AssigmentStatementNode.Operator.PLUSASSIGN; }
  | "-="   { op = AssigmentStatementNode.Operator.MINUSASSIGN; }
  | "<<="  { op = AssigmentStatementNode.Operator.LSHIFTASSIGN; }
  | ">>="  { op = AssigmentStatementNode.Operator.RSIGNEDSHIFTASSIGN; }
  | ">>>=" { op = AssigmentStatementNode.Operator.RUNSIGNEDSHIFTASSIGN; }
  | "&="   { op = AssigmentStatementNode.Operator.ANDASSIGN; }
  | "^="   { op = AssigmentStatementNode.Operator.XORASSIGN; }
  | "|="   { op = AssigmentStatementNode.Operator.ORASSIGN; }
  )
  {    return op;
  }
}

ExpressionNode ConditionalExpression():
{
  ExpressionNode finalNode, auxNode1, auxNode2;
}
{
  finalNode = ConditionalOrExpression()
  
  [ "?" auxNode1=Expression() ":" auxNode2=Expression()
    {
      finalNode = new TernaryExpressionNode(finalNode, auxNode1, auxNode2);
    }
  ]
  {
    return finalNode;  }
}

ExpressionNode ConditionalOrExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  LogicalOperation.Operator operator;
}
{
  finalNode = ConditionalAndExpression()
  ( "||" { operator = LogicalOperation.Operator.OR; }
    auxiliarNode = ConditionalAndExpression()
    {
      finalNode = new LogicalOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode ConditionalAndExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  LogicalOperation.Operator operator;
}
{
  finalNode = InclusiveOrExpression()
  ( "&&" { operator = LogicalOperation.Operator.AND; }
    auxiliarNode = InclusiveOrExpression()
    {
      finalNode = new LogicalOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode InclusiveOrExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  MathematicOperation.Operator operator;
}
{
  finalNode = ExclusiveOrExpression()
  ( "|" { operator = MathematicOperation.Operator.BIT_OR; }
    auxiliarNode = ExclusiveOrExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode ExclusiveOrExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  MathematicOperation.Operator operator;
}
{
  finalNode = AndExpression()
  ( "^" { operator = MathematicOperation.Operator.BIT_XOR; }
    auxiliarNode = AndExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode AndExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  MathematicOperation.Operator operator;
}
{
  finalNode = EqualityExpression()
  ( "&" { operator = MathematicOperation.Operator.BIT_AND; }
    auxiliarNode = EqualityExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode EqualityExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  BooleanOperation.Operator operator;
}
{
  finalNode = InstanceOfExpression()
  (
    ( "==" { operator = BooleanOperation.Operator.EQ; }
    | "!=" { operator = BooleanOperation.Operator.NEQ; }
    )
    auxiliarNode = InstanceOfExpression()
    {
      finalNode = new BooleanOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {    return finalNode;
  }
}

ExpressionNode InstanceOfExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  BooleanOperation.Operator operator;
  Token t;
  BaseType type;
}
{
  finalNode = RelationalExpression()
  [ t="instanceof" { operator = BooleanOperation.Operator.INSTANCEOF; }
    type = Type()
    {
      auxiliarNode = new TypeDataAccess(type,new CodeZoneClass(t,file));
      finalNode = new BooleanOperation(operator,finalNode,auxiliarNode);    }
  ]
  {
    return finalNode;
  }
}

ExpressionNode RelationalExpression():
{
  ExpressionNode finalNode, auxiliarNode;
  BooleanOperation.Operator operator;
}
{
  finalNode = ShiftExpression()
  (
    ( "<" { operator = BooleanOperation.Operator.LT; }
    | ">" { operator = BooleanOperation.Operator.GT; }
    | "<=" { operator = BooleanOperation.Operator.LE; }
    | ">=" { operator = BooleanOperation.Operator.GE; }
    )
    auxiliarNode = ShiftExpression()
    {
      finalNode = new BooleanOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode ShiftExpression():
{
    ExpressionNode finalNode, auxiliarNode;
    MathematicOperation.Operator operator;
}
{
  finalNode = AdditiveExpression()
  (
    ( "<<" { operator = MathematicOperation.Operator.LEFT_SHIFT; }
    | RSIGNEDSHIFT()
           { operator = MathematicOperation.Operator.RIGHT_SHIFT; }
    | RUNSIGNEDSHIFT()
           { operator = MathematicOperation.Operator.RIGHT_UNSIGNED_SHIFT; }
    )
    auxiliarNode = AdditiveExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode AdditiveExpression():
{
    ExpressionNode finalNode, auxiliarNode;
    MathematicOperation.Operator operator;
}
{
  finalNode = MultiplicativeExpression()
  (
    (   "+" { operator = MathematicOperation.Operator.ADD; }
      | "-" { operator = MathematicOperation.Operator.SUB;  }
    )
    auxiliarNode = MultiplicativeExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);
    }
  )*
  {
    return finalNode;
  }
}

ExpressionNode MultiplicativeExpression():
{
    List<PrintInfo> out = new LinkedList<PrintInfo>();
    ExpressionNode finalNode, auxiliarNode;
    MathematicOperation.Operator operator;
}
{
  finalNode = UnaryExpression()
  (
    (   "*" { operator = MathematicOperation.Operator.MUL; }
	  | "/" { operator = MathematicOperation.Operator.DIV; }
	  | "%" { operator = MathematicOperation.Operator.MOD; }
	)
    auxiliarNode = UnaryExpression()
    {
      finalNode = new MathematicOperation(operator,finalNode,auxiliarNode);    }
  )*
  {    return finalNode;
  }
}

ExpressionNode UnaryExpression():
{
  ExpressionNode finalNode;
  UnaryOperation.Operator operator;
  Token t;
}
{
  (
    ( t="+" { operator = null; }
    | t="-" { operator = UnaryOperation.Operator.NEGATE; } )
    finalNode = UnaryExpression()
    {
      if(operator != null)
        finalNode = new UnaryOperation( operator, finalNode, t );    }
  | finalNode = PreIncrementExpression()
  | finalNode = PreDecrementExpression()
  | finalNode = UnaryExpressionNotPlusMinus()
  )
  
  {
    return finalNode;
  }
}

ExpressionNode PreIncrementExpression():
{
  ExpressionNode node;
  Token t;
}
{
  t="++"
  node = PrimaryExpression()
  
  {
    return new UnaryOperation( UnaryOperation.Operator.PRE_INC, node, t );
  }
}

ExpressionNode PreDecrementExpression():
{
  ExpressionNode node;
  Token t;
}
{
  t = "--"
  node = PrimaryExpression()
  
  {
    return new UnaryOperation( UnaryOperation.Operator.PRE_DEC, node, t );
  }
}

ExpressionNode UnaryExpressionNotPlusMinus():
{
  List<PrintInfo > out = new LinkedList<PrintInfo >();
  ExpressionNode finalNode;
  UnaryOperation.Operator operator;
  Token t;
}
{
  (
    ( t = "~" { operator = UnaryOperation.Operator.BIT_COMP; }
    | t = "!" { operator = UnaryOperation.Operator.NOT; }
    )
     finalNode = UnaryExpression()
     {
       finalNode = new UnaryOperation( operator, finalNode, t );     }
  |
    LOOKAHEAD( CastLookahead() )
    finalNode = CastExpression()
  |
    finalNode = PostfixExpression()
  )
  
  {
    return finalNode;
  }
}

// This production is to determine lookahead only.  The LOOKAHEAD specifications
// below are not used, but they are there just to indicate that we know about
// this.
void CastLookahead():
{
}
{
  LOOKAHEAD(2)
  "(" PrimitiveType()
|
  LOOKAHEAD("(" Type() "[")
  "(" Type() "[" "]"
|
  "(" Type() ")" ( "~" | "!" | "(" | <IDENTIFIER> | "this" | "super" | "new" | Literal() )
}

ExpressionNode PostfixExpression():
{
  ExpressionNode finalNode;
  Token t;
  UnaryOperation.Operator operator;
}
{
  finalNode = PrimaryExpression()
  [ ( t="++" {operator = UnaryOperation.Operator.POST_INC;} | t="--" {operator = UnaryOperation.Operator.POST_DEC;})
    {
      finalNode = new UnaryOperation(operator, finalNode, t);    }
  ]

  {    return finalNode;
  }
}

ExpressionNode CastExpression():
{
  ExpressionNode finalNode;
  BaseType type;
  Token t;

  List<PrintInfo> out = new LinkedList<PrintInfo>();
}
{
  (
    LOOKAHEAD("(" PrimitiveType())
    t="(" type=Type() ")" finalNode = UnaryExpression()
  |
    t="(" type=Type() ")" finalNode = UnaryExpressionNotPlusMinus()
  )
  {
    return new CastExpressionNode(t, type, finalNode);
  }
}

ExpressionNode PrimaryExpression():
{
  ExpressionNode result;
}
{
  result = PrimaryPrefix()
  ( LOOKAHEAD(2)
    result = PrimarySuffix(result)
  )*

  {    return result;
  }
}

ExpressionNode MemberSelector(ExpressionNode in):
{
  Token t, t2;
}
{
  t="." TypeArguments() t2=<IDENTIFIER>
  {
    //TODO arguments
    return new ProxyDataAccess( "parametrized " + t.image, in, new CodeZoneClass(t, t2, file));
  }
}

ExpressionNode PrimaryPrefix():
{
  List<PrintInfo> out = new LinkedList<PrintInfo>();
  Token t, t2;
  ExpressionNode result;
  List<Token> tokenList = new LinkedList<Token>();
  BaseType type;
}
{
  (
    result = Literal()
  |
    LOOKAHEAD( ( <IDENTIFIER> "." )* "this" )
    ( t=<IDENTIFIER> "."
      {
        tokenList.add(t);
      }
    )*
    t="this"
    {
      //Code zone things
      if(tokenList.size() > 0) {
        //TODO algo
        result = new ProxyExpression(tokenList.get(0).image + " ... this",
                                     new CodeZoneClass(tokenList.get(0),t,file));      } else      {
        BaseSymbol symbol = symbolTable.findSymbol("this");
        if(symbol != null) {
          result = new LocalVarAccess((LocalVariableSymbol)symbol, new CodeZoneClass(t,file));        } else {          result = new ProxyDataAccess("this", new CodeZoneClass(t,file));
        }      }
    }
  |
    t="super" "." t2=<IDENTIFIER>
    {
      //TODO
      result = new ProxyExpression("super." + t2.image, new CodeZoneClass(t, t2,file));
    }
  |
     // danson, added this part to support a construct like:
     //   Buffer.super.setDirty(true);
     // See Java Language Specification, 3rd edition, section 15.11.2.
     LOOKAHEAD( ClassOrInterfaceType() "." "super" "." <IDENTIFIER> )
     type = ClassOrInterfaceType() t="." "super" "." t2=<IDENTIFIER>
     {
       //TODO
      result = new ProxyExpression(type + ".super." + t.image, new CodeZoneClass(t, t2,file));
     }
  |
    "(" result = Expression() ")"
  |
    result = AllocationExpression(null)
  |
    LOOKAHEAD( ResultType() "." "class" )
    type = ResultType() t="." t2="class"
    {
      result = new LiteralData.ClassLiteral(type, new CodeZoneClass(t, t2,file));
    }
  |
    {
      List<Token> aux;    }
    aux = Name()
    {
      result = Utils.resolveName(symbolTable,aux,file);    }
  )
  {
    return result;  }
}

ExpressionNode PrimarySuffix(ExpressionNode in):
{
  Token t, t2;
  ExpressionNode out;
}
{
  ( 
      LOOKAHEAD("." "super" ".")
      t="." t2="super"
      {
        out = new ProxyExpression(".super",new CodeZoneClass(t,t2,file));
      }
    |
      LOOKAHEAD("." "this")
      t="." t2="this"
      {
        out = new ProxyExpression(".this",new CodeZoneClass(t,t2,file));
      }
    |
      LOOKAHEAD(2)
      "."
      out = AllocationExpression(in)
    |
      LOOKAHEAD(3)
      out = MemberSelector(in)
    |
      "["
      {
        ExpressionNode access;
      }
      access = Expression() t="]"
      {
        out = new ArrayOrComponentAccess(in, access, t);
      }
    |
      "." t = <IDENTIFIER>
      {
        out = Utils.accessToMember( in, t.image, t);
      }
    |
      {
        CallToArguments args;      }
      args = Arguments()
      {
        DataAccess method;
        if(in instanceof DataAccess)        {
          method = (DataAccess) in;        } else {          method = new ProxyDataAccess("Method Call",in);
        }
        out = new CallToMethod(method,args);
      }
  )
  {    return out;
  }
}

LiteralData Literal():
{
  Token t;
  LiteralData data;
}
{
  (    
    t=<INTEGER_LITERAL>
    {
      data = new LiteralData.IntegerLiteral(t,file);
    }
  |
    t=<FLOATING_POINT_LITERAL>
    {
      data = new LiteralData.FloatLiteral(t,file);
    }
  |
    t=<CHARACTER_LITERAL>
    {
      data = new LiteralData.CharacterLiteral(t,file);
    }
  |
    t=<STRING_LITERAL>
    {
      data = new LiteralData.StringLiteral(t,file);
    }
  |
    data = BooleanLiteral()
  |
    data = NullLiteral()
  )
  {    return data;
  }
}

LiteralData BooleanLiteral():
{
  Token t;
  LiteralData lit;
}
{
  (    
  t="true"
  {
    lit = new LiteralData.TrueLiteral(t,file);
  }
|
  t="false"
  {
    lit = new LiteralData.FalseLiteral(t,file);
  }
)
  {    return lit;
  }
}

LiteralData NullLiteral():
{
  Token t;
}
{
  t = "null"
  {
    return new LiteralData.NullLiteral(t,file);
  }
}

CallToArguments Arguments():
{
  //List<PrintInfo> other = new LinkedList<PrintInfo>();
  List<ExpressionNode> arguments = new LinkedList<ExpressionNode>();
  Map<String,ExpressionNode> argNames = new HashMap<String,ExpressionNode>();
  ExpressionNode node;
  Token t, t2, argumentName;
  CallToArguments result;
}
{
  t="("
      (
        LOOKAHEAD( < IDENTIFIER > ":" )
        argumentName = < IDENTIFIER >
        ":"
        node = VariableInitializer(UnknownType.empty)//TODO
        {
          argNames.put(argumentName.image, node);
        }
        (
          ","
          argumentName = < IDENTIFIER >
          ":"
          node = VariableInitializer(UnknownType.empty)//TODO
          {
            argNames.put(argumentName.image, node);
          }        )*
        t2=")"
        {
          result = new CallToNamedArguments(argNames, new CodeZoneClass(t,t2,file));        }

      | //non-named arguments
        node = Expression()
        {
          arguments.add(node);        }
        ( ","
          node = Expression()
          {
            arguments.add(node);
          }
        )*
        t2=")"
        {
          result = new CallToListedArguments(arguments, new CodeZoneClass(t,t2,file));
        }
      | 
        t2=")"
        {
          result = new CallToListedArguments(arguments, new CodeZoneClass(t,t2,file));
        }
      )
        
  {
    return result;
  }
}

ExpressionNode AllocationExpression(ExpressionNode in):
{
  List<PrintInfo> other  = new LinkedList<PrintInfo>()
                , other2 = new LinkedList<PrintInfo>()
                , out    = new LinkedList<PrintInfo>();

  ExpressionNode exp;
  BaseType type;
  CallToArguments args;
  Token t;
}
{
  (
    
    LOOKAHEAD(2)
    t="new" type = PrimitiveType() exp = ArrayDimsAndInits(type, t)
  |
    t="new"
    type = ClassOrInterfaceType()
    [ TypeArguments()
      //TODO
    ]
      (
        exp = ArrayDimsAndInits(type, t)
      |
        args = Arguments()

        
        (           ClassOrInterfaceBody(false, out)
           //TODO Fer inner classes?
           {
             //TODO
             exp = new ProxyExpression(out);
             exp = new UnaryProxy("new " + type.toString(), exp);
           }
        |
        {
          if(in == null) {
            exp = new AllocationExpressionNode(type, args,t);
          } else {
            exp = new AllocationExpressionNode(in,type, args,t);          }        }
        ) 
      )
  )
  {    return exp;
  }
}

/*
 * The third LOOKAHEAD specification below is to parse to PrimarySuffix
 * if there is an expression between the "[...]".
 */
ExpressionNode ArrayDimsAndInits(BaseType in, Token n):
{
  ExpressionNode result, aux;
  List<ExpressionNode> listLengths = new LinkedList<ExpressionNode>();
  int dims = 0;

  Token t;
}
{
  (
    LOOKAHEAD(2)
    ( LOOKAHEAD(2) "[" 
      aux = Expression() t="]"
      {
        listLengths.add(aux);
        dims++;
      }
    )+
    ( LOOKAHEAD(2) "[" t="]"
      {
        dims++;
      }
    )*
    {
      result = new ArrayAllocationExpressionNode(
                    in, 
                    listLengths.toArray(new ExpressionNode[listLengths.size()]),
                    dims,
                    new CodeZoneClass(n, t,file));    }
  |
    ( "[" "]"
      {
        //TODO algo aqui i no se el que...
      }
    )+
    result = ArrayInitializer(in)
  )
  {    return result;
  }
}


/*
 * Statement syntax follows.
 */

StatementNode Statement():
{
  StatementNode statement;
}
{
  (
    LOOKAHEAD(2)
    statement = LabeledStatement()
  |
    statement = AssertStatement()
  |
    statement = Block()
  |
    statement = EmptyStatement()
  |
    statement = StatementExpression() ";"
  |
    statement = SwitchStatement()
  |
    statement = IfStatement()
  |
    statement = WhileStatement()
  |
    statement = DoStatement()
  |
    statement = ForStatement()
  |
    statement = BreakStatement()
  |
    statement = ContinueStatement()
  |
    statement = ReturnStatement()
  |
    statement = ThrowStatement()
  |
    statement = SynchronizedStatement()
  |
    statement = TryStatement()
  )
  {
    return statement;  }
}

AssertStatementNode AssertStatement():
{
  ExpressionNode assertion, message=null;
  Token t, t2;
}
{
  t = "assert"
  assertion = Expression()
  [ ":"
    message = Expression()
  ]
  t2 = ";"
  {
    return new AssertStatementNode(assertion, message, new CodeZoneClass(t,t2,file));
  }
}

LabeledStatementNode LabeledStatement():
{
  Token t;
  StatementNode node;
}
{
  t=<IDENTIFIER> ":"
  node = Statement()
  {
    return new LabeledStatementNode(t, node, symbolTable, errorLog);  }
}

BlockCode Block():
{
  StatementNode blockStatementNode;
  Token t;

  BlockCode.TmpBlockCode prevBlock = localBlock;
  symbolTable.newContext();
}
{
  t = "{"
  {
    localBlock = new BlockCode.TmpBlockCode(t,file);
  }
  ( 
    blockStatementNode = BlockStatement()
    {
      localBlock.addStatement(blockStatementNode);
    }
  )*
  t="}"
  {

    localBlock.setEndToken(t);
    BlockCode block = localBlock.transformToBlockCode();


    localBlock = prevBlock;

    symbolTable.deleteContext();
    return block;
  }
}

StatementNode BlockStatement():
{
  List<PrintInfo> out = new LinkedList<PrintInfo>();
  Token t;
  StatementNode result;
}
{
  (    LOOKAHEAD( Modifiers() Type() <IDENTIFIER> )
    result = LocalVariableDeclaration() t=";"
  |
    result = Statement()
  |
    ClassOrInterfaceDeclaration(0, out)
    {
      //TODO
      result = new NoOpStatement();
    }
  )
  {    return result;
  }
}

StatementList LocalVariableDeclaration():
{
  int modifiers;
  BaseType type;
  VarAndInit var;
  List<PrintInfo> out = new LinkedList<PrintInfo>();

  List<StatementNode > initializers = new LinkedList<StatementNode >();
}
{
  modifiers=Modifiers(out) type = Type() var=VariableDeclarator(modifiers,type)
  {
    if(var.init != null) {
      initializers.add(var.init);    }  }
  
  ( ","
    var = VariableDeclarator(modifiers,type)
    {
      if(var.init != null) {
        initializers.add(var.init);
      }
    }
  )*
  {
    return new StatementList(initializers.toArray(new StatementNode[initializers.size()]));  }
}

NoOpStatement EmptyStatement():
{
  Token t;
}
{
  t = ";"
  {
    return new NoOpStatement(new CodeZoneClass(t,file));  }
}

StatementNode StatementExpression():
/*
 * The last expansion of this production accepts more than the legal
 * Java expansions for StatementExpression.  This expansion does not
 * use PostfixExpression for performance reasons.
 */
{
  ExpressionNode expression, expression2;
  Token t;
  AssigmentStatementNode.Operator assignOperator;
  StatementNode statementNode;
}
{
  (
    ( expression = PreIncrementExpression()
    | expression = PreDecrementExpression()
    )
    {
      statementNode = new StatementFromExpresion(expression);    }
  |
    expression = PrimaryExpression()
    (
      ( t = "++"
      | t = "--"
      )
      {
        expression = new UnaryOperation(UnaryOperation.Operator.PRE_INC,
                                       expression, t);
        statementNode = new StatementFromExpresion(expression);
      }
    |
      assignOperator = AssignmentOperator()
      expression2 = Expression()
      {
        statementNode = new AssigmentStatementNode(assignOperator,
                                                   expression,
                                                   expression2);      }
    |
    {
      statementNode = new StatementFromExpresion(expression);    }    ) 
  )
  {    return statementNode;
  }
}

SwitchStatementNode SwitchStatement():
{
  Token t, t2;

  ExpressionNode in, label;
  List<StatementNode> statements;
  List<SwitchStatementNode.CaseNode> cases = new LinkedList<SwitchStatementNode.CaseNode>();
  StatementNode bsn;
}
{
  t="switch" "("
  in=Expression() ")" "{"
  {
    BlockCode.TmpBlockCode prevBlock = localBlock;
    symbolTable.newContext();
    localBlock = new BlockCode.TmpBlockCode(t,file);  }
  (
    label = SwitchLabel()
    {      statements = new LinkedList<StatementNode>();
    }
    (
      bsn = BlockStatement()
      {
        statements.add(bsn);
      }
    )*
    {
      cases.add(new SwitchStatementNode.CaseNode(label,statements));
    }
  )*
  t2="}"
  {
    SwitchStatementNode node =  new SwitchStatementNode(in, cases,
                                                        localBlock.localVariables,
                                                        new CodeZoneClass(t,t2,file));
    
    localBlock = prevBlock;
    symbolTable.deleteContext();
    return node;
  }
}

ExpressionNode SwitchLabel():
{
  ExpressionNode cas;
}
{
  (    "case" cas = Expression() ":"
  |
    "default" ":"
    {
      cas = null;
    }
  )
  {
    return cas;  }
}

IfStatementNode IfStatement():
/*
 * The disambiguating algorithm of JavaCC automatically binds dangling
 * else's to the innermost if statement.  The LOOKAHEAD specification
 * is to tell JavaCC that we know what we are doing.
 */
{
  StatementNode node1, node2 = null;
  ExpressionNode expression;
  Token t;
}
{
  t="if" "("
  expression = Expression()
  ")"
  {
    symbolTable.newContext();
  }
  node1 = Statement()
  {
    symbolTable.deleteContext();
  }
  [    LOOKAHEAD(1) "else"
    {
      symbolTable.newContext();
    }
    node2 = Statement()
    {
      symbolTable.deleteContext();
    }
  ]
  {
    return new IfStatementNode( t, expression, node1, node2);  }
}

WhileStatementNode WhileStatement():
{
  Token t;
  ExpressionNode condition;
  StatementNode execution;
}
{
  t="while" "("
  condition = Expression()
  ")"
  execution = Statement()

  {
    return new WhileStatementNode(condition, execution,
                                new CodeZoneClass(t,execution));  }
}

DoStatementNode DoStatement():
{
  Token t, t2;
  ExpressionNode condition;
  StatementNode execution;
}
{
  t = "do"
  execution = Statement()
  "while" "("
  condition = Expression()
  ")" t2 = ";"
  {
    return new DoStatementNode(execution, condition, new CodeZoneClass(t,t2,file));
  }
}

StatementNode ForStatement():
{
  Token t, t2;

  List<PrintInfo> out = new LinkedList<PrintInfo>();

  StatementNode init, update, execution;
  ExpressionNode condition;

  int mods;
  BaseType type;
  ExpressionNode iterable;

  StatementNode result;
  
  BlockCode.TmpBlockCode prevBlock = localBlock;
  symbolTable.newContext();
}
{
  t="for" "("
  {    localBlock = new BlockCode.TmpBlockCode(t,file);
  }

  (
      LOOKAHEAD(Modifiers() Type() <IDENTIFIER> ":")
      mods = Modifiers(out) type = Type() t2=<IDENTIFIER> ":"
      iterable = Expression()
      {
        LocalVariableSymbol it = new LocalVariableSymbol(mods, type, t2.image);
        symbolTable.addSymbol(it);
        localBlock.addLocalVariable(it);
      }

      ")" execution = Statement()

      {
        result = new IterableFor(it,
                                 iterable,
                                 execution,
                                 new CodeZoneClass(t, execution)
                                );      }
    |  // -------------------------------------------------------------------
      (        init = ForInit() ";"
      |
        t2 = ";"
        {
          init = new NoOpStatement(new CodeZoneClass(t2,t2,file));         }
      )

      (         condition = Expression() ";"
      |
        t2 = ";"
        {
          condition = new LiteralData.TrueLiteral(t2,file);        }
      )

      (        update = ForUpdate() ")"
      |
        t2 = ")"
        {
          update = new NoOpStatement(new CodeZoneClass(t2,t2,file));         }
      )
      execution = Statement()
      {
        result = new ClassicFor(localBlock.localVariables,
                                init,condition,update,execution,
                                new CodeZoneClass(t,execution));      }
  )

  {    localBlock = prevBlock;
    symbolTable.deleteContext();

    return result;
  }
}

StatementNode ForInit():
{
  StatementNode result;
}
{
  (
    LOOKAHEAD( Modifiers() Type() <IDENTIFIER> )
    result = LocalVariableDeclaration()
  |
    result = StatementExpressionList()
  )
  {    return result;
  }
}

StatementNode StatementExpressionList():
{
  StatementNode statement;
  List<StatementNode> statements = new LinkedList<StatementNode>();
}
{
  statement = StatementExpression()
  {    statements.add(statement);
  }
  ( ","
    statement = StatementExpression()
    {
      statements.add(statement);      
    }
  )*
  {
    statement = new StatementList(statements.toArray(new StatementNode[statements.size()]));
    
    return statement;  }
}

StatementNode ForUpdate():
{
  StatementNode aux;
}
{
  aux = StatementExpressionList()
  {    return aux;
  }
}

JumpStatement BreakStatement():
{
  Token t = null, t2, t3;
}
{
  t2="break" [ t=<IDENTIFIER> ] t3=";"
  {
    return new JumpStatement( JumpStatement.Operator.BREAK,
                              (t == null)? null : t.image,
                              new CodeZoneClass(t2,t3,file));                                
  }
}

JumpStatement ContinueStatement():
{
  Token t = null, t2, t3;
}
{
  t2 = "continue" [ t=<IDENTIFIER> ] t3 = ";"
  {
    return new JumpStatement( JumpStatement.Operator.CONTINUE,
                              (t == null)? null : t.image,
                              new CodeZoneClass(t2,t3,file));
                                
  }
}

ReturnStatementNode ReturnStatement():
{
  Token t, t2;
  ExpressionNode exp = null;
}
{
  t="return"
  [ exp=Expression() ] t2=";"
  {
    return new ReturnStatementNode(exp, new CodeZoneClass(t, t2,file));
  }
}

ThrowStatementNode ThrowStatement():
{
  Token t, t2;
  ExpressionNode exp = null;
}
{
  t="throw" exp = Expression() t2=";"
  {
    return new ThrowStatementNode(exp, new CodeZoneClass(t, t2,file));
  }
}

SynchronizedStatementNode SynchronizedStatement():
{
  Token t;
  ExpressionNode exp;
  BlockCode block;
}
{
  t="synchronized" "("
  exp = Expression()
  ")"
  block = Block()
  {
    return new SynchronizedStatementNode(exp, block,
                                        new CodeZoneClass(t,block));  }
}

TryStatementNode TryStatement():
/*
 * Semantic check required here to make sure that at least one
 * finally/catch is present.
 */
{
  ParameterClass param;
  Token t;
  CodeZone cz;

  BlockCode execution, aux, finalment = null;
  List<TryStatementNode.CatchBlock> catches = new LinkedList<TryStatementNode.CatchBlock>();
}
{
  t = "try"
  execution = Block()
  {
    cz = new CodeZoneClass(t, execution);  }
  ( "catch" "("
    param = FormalParameter()
    ")"
    {
      LocalVariableSymbol symbol = new LocalVariableSymbol(param.modifiers,
	                                                       param.type,
	                                                       param.name);
      symbolTable.newContext();
      symbolTable.addSymbol(symbol);
    }
    aux = Block()
    {
      symbolTable.deleteContext();
      catches.add(new TryStatementNode.CatchBlock(symbol, aux));
      cz = new CodeZoneClass(cz, aux);    }
  )*
  [ "finally"
    finalment = Block()
    {
      cz = new CodeZoneClass(cz, finalment);    }
  ]
  {
    return new TryStatementNode(execution, catches, finalment, cz);  }
}

/* We use productions to match >>>, >> and > so that we can keep the
 * type declaration syntax with generics clean
 */

void RUNSIGNEDSHIFT():
{}
{
  ( LOOKAHEAD({ getToken(1).kind == GT &&
                ((cat.quadriga.parsers.tokens.MySimpleToken)getToken(1)).realKind == RUNSIGNEDSHIFT} )
   ">" ">" ">"
  )
}

void RSIGNEDSHIFT():
{}
{
  ( LOOKAHEAD({ getToken(1).kind == GT &&
                ((cat.quadriga.parsers.tokens.MySimpleToken)getToken(1)).realKind == RSIGNEDSHIFT} )
  ">" ">"
  )
}

/* Annotation syntax follows. */

void Annotation(List<PrintInfo> out):
{}
{
   LOOKAHEAD( "@" Name() "(" ( <IDENTIFIER> "=" | ")" ))
   NormalAnnotation(out)
 |
   LOOKAHEAD( "@" Name() "(" )
   SingleMemberAnnotation(out)
 |
   MarkerAnnotation(out)
}

void NormalAnnotation(List<PrintInfo> out):
{
}
{
   "@"
   {
     out.add(new PrintString("@"));
   }
   Name()
   "("
   {
     out.add(PrintWhiteSpace.getInstance());
     out.add(new PrintString("("));
   }
   [ MemberValuePairs(out) ] ")"
   {
     out.add(new PrintString(")"));
   }
}

void MarkerAnnotation(List<PrintInfo> out):
{}
{
  "@"
   {
     out.add(new PrintString("@"));
   }
   Name()
}

void SingleMemberAnnotation(List<PrintInfo> out):
{}
{
  "@"
   {
     out.add(new PrintString("@"));
   }
   Name() "("
   {
     out.add(PrintWhiteSpace.getInstance());
     out.add(new PrintString("("));
   }
   MemberValue(out)
   ")"
   {
     out.add(new PrintString(")"));
   }
}

void MemberValuePairs(List<PrintInfo> out):
{}
{
   MemberValuePair(out)
   ( ","
     {
       out.add(PrintWhiteSpace.getInstance());
       out.add(new PrintString(","));
     }
     MemberValuePair(out)
   )*
}

void MemberValuePair(List<PrintInfo> out):
{
  Token t;
}
{
   t=<IDENTIFIER> "="
   {
     out.add(new PrintString(t.image));
     out.add(PrintWhiteSpace.getInstance());
     out.add(new PrintString("="));
     out.add(PrintWhiteSpace.getInstance());
   }
   MemberValue(out)
}

void MemberValue(List<PrintInfo> out):
{}
{
   Annotation(out)
 |
   MemberValueArrayInitializer(out)
 |
   ConditionalExpression()
}

void  MemberValueArrayInitializer(List<PrintInfo> out):
{}
{
  "{"
  {
    out.add(new PrintString("{"));
    out.add(PrintInitTab.getInstance());
    out.add(PrintIntro.getInstance());
  }
  ( MemberValue(out)
    ( LOOKAHEAD(2) ","
    {
      out.add(new PrintString("}"));
      out.add(PrintWhiteSpace.getInstance());
    }
      MemberValue(out)
    )* [ "," ]
  )?
  "}"
  {
    out.add(PrintEndTab.getInstance());
    out.add(PrintIntro.getInstance());
    out.add(new PrintString("}"));
  }
}


/* Annotation Types. */

void AnnotationTypeDeclaration(int modifiers, List<PrintInfo> out):
{
  Token t;
}
{
  "@" "interface" t=<IDENTIFIER>
  {
    out.add(new PrintString("@"));
    out.add(PrintWhiteSpace.getInstance());
    out.add(new PrintString("interface"));
    out.add(PrintWhiteSpace.getInstance());
    out.add(new PrintString(t.image));
    out.add(PrintWhiteSpace.getInstance());
  }
  AnnotationTypeBody(out)
}

void AnnotationTypeBody(List<PrintInfo> out):
{}
{
  "{"
  {
    out.add(new PrintString("{"));
    out.add(PrintInitTab.getInstance());
    out.add(PrintIntro.getInstance());
  }
  ( AnnotationTypeMemberDeclaration(out) )*
  "}"
  {
    out.add(PrintEndTab.getInstance());
    out.add(PrintIntro.getInstance());
    out.add(new PrintString("}"));
  }
}

void AnnotationTypeMemberDeclaration(List<PrintInfo> out):
{
   int modifiers;
   Token t;
}
{
 modifiers = Modifiers(out)
 (
   LOOKAHEAD(Type() <IDENTIFIER> "(")
   Type() t=<IDENTIFIER> "(" ")"
   {
     out.add(new PrintString(t.image));
     out.add(new PrintString("("));
     out.add(new PrintString(")"));
   }
   [ DefaultValue(out) ] ";"
   {
     out.add(new PrintString(";"));
   }
  |
   ClassOrInterfaceDeclaration(modifiers, out)
  |
   EnumDeclaration(modifiers, out)
  |
   AnnotationTypeDeclaration(modifiers, out)
  |
   FieldDeclaration(modifiers, out)
 )
 |
   ( ";" )
}

void DefaultValue(List<PrintInfo> out):
{}
{
  "default"
  {
     out.add(new PrintString("default"));
     out.add(PrintWhiteSpace.getInstance());
  }
  MemberValue(out)
}
// *************************************************************************
// *************************************************************************
// *************************************************************************
// *************************************************************************
// *************************************************************************

// Coses de quadriga a partir d'aqui:

void QuadrigaUnit():
{
  String packa;}
{
  packa = QuadrigaPackageDeclaration()

  ( QuadrigaDeclaration() [";"] )+    

  ( < "\u001a" > )?
  ( <STUFF_TO_IGNORE_BIS: ~[]> )?
  <EOF>}

BaseType QuadrigaEntity():
{
  List<ParametrizedClass.ParameterClass> components = null;
  Token t;}{
  t="Entity"
  [components = TypeArguments()]
  {
    if(components != null) {
      CodeZone cz = new CodeZoneClass(t,file);      Set<QuadrigaComponent> componentSet = new HashSet<QuadrigaComponent>();
      for(ParametrizedClass.ParameterClass param : components) {
        if(param.bound != ParametrizedClass.ParameterClass.Bound.NO) {
          errorLog.insertError("Un paràmetre d'una entitat no pot tenir \"super\" ni \"extends\"", cz);        } else if(param.base instanceof QuadrigaComponent) {
          QuadrigaComponent component = (QuadrigaComponent)param.base;
          if(componentSet.contains(component)) {
            errorLog.insertError(component.getBinaryName() + " repetit", cz);          } else {
            componentSet.add(component);          }        } else {
          errorLog.insertError(param.base.getBinaryName() + " no és un component", cz);        }      }

      return QuadrigaEntity.getEntity(componentSet);    }    

    return QuadrigaEntity.baseEntity;  }}

String QuadrigaPackageDeclaration():
{
  List<Token> name;}
{
  "@quadriga" name = Name() [";"]
  {
    String res = "";
    boolean first = true;
    for(Token t: name) {
      if(!first) {
        res += "." + t.image;      } else {
        res = t.image;
        first = false;      }    }
    currentFile = res.replace('.', '/');
    symbolTable.addPackage("javax.vecmath");
    return res;  }}

void QuadrigaDeclaration():
{}
{
  JavaImport()
| ComponentDeclaration()
| PrototypeDeclaration()
| SystemDeclaration()
| ThreadDeclaration()}

void JavaImport():
{
  List<Token> name;}
{
  "@java"  name = Name()
  {
    String res = "";
    boolean first = true;
    for(Token t: name) {
      if(!first) {
        res += "." + t.image;
      } else {
        res = t.image;
        first = false;
      }
    }
	try {
	  Class<?> clazz = Class.forName(res);
	  BaseSymbol symbol = new TypeSymbol(ClassOrInterfaceTypeRef.getFromClass(clazz));
	  symbolTable.addGlobalSymbol(symbol);
    } catch (ClassNotFoundException e) {
	  //TODO revisar això
	  BaseSymbol symbol = new TypeSymbol(UnknownType.empty);
	  symbolTable.addGlobalSymbol(symbol);
    }
  }}

void ComponentDeclaration():
{
  Token t;
  QuadrigaComponent component = null;
  List<Token> name;
  BaseType type;
  ExpressionNode initialization = null;
}
{
  "@component" 
  (
    LOOKAHEAD( 2 ) 
    t= < IDENTIFIER >
    {
      IncompleteComponent iComponent = new IncompleteComponent(currentFile.replace('/','.'), t.image);    }
    "{"
        (
          // Dependencies
          "*" name = Name() [";"]
          {
            iComponent.addDependency(name, symbolTable, errorLog,file);            }
        )*
        ( type = Type()
          t = < IDENTIFIER >
          [ "=" initialization = VariableInitializer(type) ] [";"]
          {
            iComponent.addField(new QuadrigaComponent.ComponentField(
                                           type, t.image, initialization
                                                                ),
                                errorLog,
                                new CodeZoneClass(t,file)
                                 );          }         )*
    "}"
    {
      component = new CompleteComponent(iComponent);    }
  |
    name = Name()
    {
      String res = "";
      String dependency = null;
      for(int i = 0; i < name.size(); i++) {
        if(i == name.size() - 1)
        {
          dependency = res;
        }
        if(i != 0) {
          res += "." + name.get(i).image;
        } else {
          res = name.get(i).image;
        }
      }
      if(name.size() == 1)      {
        component = new ProxyComponent(currentFile.replace('/','.') + '.' + res);      } else      {
        BaseSymbol symbol = symbolTable.findSymbol(res);
        if(symbol != null) {
          if(symbol instanceof TypeSymbol
             && ((TypeSymbol)symbol).type instanceof QuadrigaComponent)
          {
            component = null; //Ja hi és a la taula de símbols          } else          {
            component = new ProxyComponent(res);
            errorLog.insertError("El símbol " + res + " no és un component",
                                 new CodeZoneClass(name.get(0),name.get(name.size()-1),file));          }        } else {          component = new ProxyComponent(res);
          addDependency(dependency);
        }
      }
    }
  )
  {
    if(component != null) {
      BaseSymbol symbol = new TypeSymbol(component);
	  symbolTable.addSymbol(symbol);
    }
  }
}

void PrototypeDeclaration():
{
  Token t;
  QuadrigaPrototype prototype = null;
  List<Token> name;
  List<ParameterClass> parameters = new LinkedList<ParameterClass>();
  ComponentAllocation componentAllocation;
  ApplyPrototypeToEntity proto;
  ExpressionNode thisEntity;
  BlockCode blockAux;
}
{
  "@prototype" 
  (
    LOOKAHEAD( 2 ) 
    t= < IDENTIFIER >
    {
      IncompletePrototype iPrototype = new IncompletePrototype(currentFile.replace('/','.'), t.image);
      symbolTable.newContext();
      symbolTable.addSymbol(new ThisSymbol(iPrototype));

      BlockCode.TmpBlockCode prevBlock = localBlock;
      localBlock = new BlockCode.TmpBlockCode(t,file);    }
    ( parameters=FormalParameters()
      {
        for(ParameterClass param : parameters)
        {
          LocalVariableSymbol localVar =
                                new LocalVariableSymbol(param.modifiers,
                                                        param.type,
                                                        param.name);
          symbolTable.addSymbol(localVar);
          localBlock.addLocalVariable(localVar);
        }
        iPrototype.parameters = parameters;
      }
    | {
        iPrototype.parameters = new Vector<ParameterClass>();      }
    ) 
    [ t="extends"
      {        thisEntity = new LocalVarAccess(
                                   (ThisSymbol)symbolTable.findSymbol("this"),
                                   new CodeZoneClass(t,file)
                                   );
      }
      proto=EntityInitialization(thisEntity)
      {        localBlock.addStatement(proto);      }      ( "," proto=EntityInitialization(thisEntity)        {          localBlock.addStatement(proto);        }      )*
    ] 
    "{"
        (          componentAllocation = ComponentDeclarator() [";"]
          {
            thisEntity = new LocalVarAccess(
                                   (ThisSymbol)symbolTable.findSymbol("this"),
                                   componentAllocation
                                   );
            localBlock.addStatement( new AddComponentNode(componentAllocation,
                                                          thisEntity,
                                                          componentAllocation)
                                        );          }
        |
          "@child" t="{"
              (
                {
                  ExpressionNode entityCreation, expAux;                }               (
                 LOOKAHEAD(Expression() ":")                 expAux = Expression() t=":"
                 {
                   CodeZoneClass czaux = new CodeZoneClass(expAux,t);
                   thisEntity = new LocalVarAccess(
                           (ThisSymbol)symbolTable.findSymbol("this"),
                           czaux
                           );
                   entityCreation = new NewEntity(thisEntity,expAux,czaux);                 }
               |                 {
                   CodeZoneClass czaux = new CodeZoneClass(t,file);
                   thisEntity = new LocalVarAccess(
                           (ThisSymbol)symbolTable.findSymbol("this"),
                           czaux
                           );
                   entityCreation = new NewEntity(thisEntity,null,czaux);                 }
               )

               proto = EntityInitialization(entityCreation) [t=";"]
               {
                 localBlock.addStatement(proto);               }
              )*
          "}"
        | "@init" blockAux=Block()
          {
            localBlock.addStatement(blockAux);          }
        )*
    t="}"
    {
      localBlock.setEndToken(t);
      iPrototype.initializations = localBlock.transformToBlockCode();
      localBlock = prevBlock;      symbolTable.deleteContext();
      
      prototype = new CompletePrototype(iPrototype);    }
  |
    name = Name()
    {
      String res = "";
      String dependency = null;
      for(int i = 0; i < name.size(); i++) {
        if(i == name.size() - 1)
        {
          dependency = res;
        }
        if(i != 0) {
          res += "." + name.get(i).image;
        } else {
          res = name.get(i).image;
        }
      }
      if(name.size() == 1)
      {
        prototype = new ProxyPrototype(currentFile.replace('/','.') + '.' + res);
      } else
      {
        BaseSymbol symbol = symbolTable.findSymbol(res);
        if(symbol != null) {
          if(symbol instanceof TypeSymbol
             && ((TypeSymbol)symbol).type instanceof QuadrigaPrototype)
          {
            prototype = null; //Ja hi és a la taula de símbols
          } else
          {
            prototype = new ProxyPrototype(res);
            errorLog.insertError("El símbol " + res + " no és un prototip",
                                 new CodeZoneClass(name.get(0),name.get(name.size()-1),file));
          }
        } else {
          prototype = new ProxyPrototype(res);
          addDependency(dependency);
        }
      }
    }
  )
  {
    BaseSymbol symbol = new TypeSymbol(prototype);
    symbolTable.addSymbol(symbol);
  }
}

void SystemDeclaration():
{
  List<Token> name;
  QuadrigaSystem system;
  Token t;
  QuadrigaFunction fun;}
{
  "@system"
  (
    LOOKAHEAD(2)
    t = < IDENTIFIER >
    {
      IncompleteSystem iSystem = new IncompleteSystem(currentFile.replace('/','.'),t.image);    }
    "{"
         "@components" "{"
               (Name())+
               "}"         (
           fun=QuadrigaUpdate()
           {
             if(iSystem.update == null)
             {
               iSystem.update = fun;             } else {
               errorLog.insertError("Més d'un update al sistema " + t.image, fun);             }           }         )*
    "}"
    {
      system = new CompleteSystem(iSystem);    }  |
    name = Name()
    {
      String res = "";
      String dependency = null;
      for(int i = 0; i < name.size(); i++) {
        if(i == name.size() - 1)
        {
          dependency = res;
        }
        if(i != 0) {
          res += "." + name.get(i).image;
        } else {
          res = name.get(i).image;
        }
      }
      if(name.size() == 1)
      {
        system = new ProxySystem(currentFile.replace('/','.') + '.' + res);
      } else
      {
        BaseSymbol symbol = symbolTable.findSymbol(res);
        if(symbol != null) {
          if(symbol instanceof TypeSymbol
             && ((TypeSymbol)symbol).type instanceof QuadrigaSystem)
          {
            system = null; //Ja hi és a la taula de símbols
          } else
          {
            system = new ProxySystem(res);
            errorLog.insertError("El símbol " + res + " no és un sistema",
                                 new CodeZoneClass(name.get(0),name.get(name.size()-1),file));
          }
        } else {
          system = new ProxySystem(res);
          addDependency(dependency);
        }
      }
    }
  )
  {
    if(system != null) {
      BaseSymbol symbol = new TypeSymbol(system);
      symbolTable.addSymbol(symbol);
    }
  }}

void ThreadDeclaration():
{
  Token t;
  List<Token> name;
  QuadrigaThread thread;
  List<QuadrigaSystem> systems = new LinkedList<QuadrigaSystem>();
  Set<String> systemNames = new HashSet<String>();
  BlockCode block = null;}
{
  "@thread"
  (
    LOOKAHEAD(2)
    t = < IDENTIFIER >
    "{"
        (
          "@system" name = Name()
          {
            String n = Utils.getName(name);
            BaseSymbol symbol = symbolTable.findSymbol(n);
            if(symbol instanceof TypeSymbol
               && ((TypeSymbol)symbol).type instanceof QuadrigaSystem)
            {
              QuadrigaSystem system = (QuadrigaSystem)((TypeSymbol)symbol).type;
              if(systemNames.contains(system.getBinaryName())) {
                errorLog.insertError("El sistema " + n + " està repetit",
                                   new CodeZoneClass(name.get(0),name.get(name.size()-1),file));              } else              {                systemNames.add(system.getBinaryName());
                systems.add(system);
              }            } else {
              errorLog.insertError("El símbol " + n + " no és un sistema",
                                   new CodeZoneClass(name.get(0),name.get(name.size()-1),file));            }          }        )+
        [ "@init" block = Block() ]
        {
          thread = new CompleteThread(currentFile.replace('/','.'),t.image,
                                      systems, block,file);        }
    "}"
  |
    name = Name()
    {
      String res = "";
      String dependency = null;
      for(int i = 0; i < name.size(); i++) {
        if(i == name.size() - 1)
        {
          dependency = res;
        }
        if(i != 0) {
          res += "." + name.get(i).image;
        } else {
          res = name.get(i).image;
        }
      }
      if(name.size() == 1)
      {
        thread = new ProxyThread(currentFile.replace('/','.') + '.' + res);
      } else
      {
        BaseSymbol symbol = symbolTable.findSymbol(res);
        if(symbol != null) {
          if(symbol instanceof TypeSymbol
             && ((TypeSymbol)symbol).type instanceof QuadrigaThread)
          {
            thread = null; //Ja hi és a la taula de símbols
          } else
          {
            thread = new ProxyThread(res);
            errorLog.insertError("El símbol " + res + " no és un thread",
                                 new CodeZoneClass(name.get(0),name.get(name.size()-1),file));
          }
        } else {
          thread = new ProxyThread(res);
          addDependency(dependency);
        }
      }
    }  )
  {
    if(thread != null) {
      BaseSymbol symbol = new TypeSymbol(thread);
      symbolTable.addSymbol(symbol);
    }  }}

ComponentAllocation ComponentDeclarator():
{
  List<Token> name;
  CallToArguments args;}
{
  name = Name() args = Arguments()
  {
    CodeZone cz = new CodeZoneClass(name.get(0), args);
    
    String symbolName = Utils.getName(name);
    BaseSymbol symbol = symbolTable.findSymbol(symbolName);
    if(symbol != null && symbol instanceof TypeSymbol) {
      BaseType type = ((TypeSymbol)symbol).type;
      if(type instanceof QuadrigaComponent) {
        CallToNamedArguments named;
        if(args instanceof CallToListedArguments)        {
          if(((CallToListedArguments)args).arguments.size() > 0) {
            errorLog.insertError("Component arguments must be named", cz);          }
          named = new CallToNamedArguments(Collections.<String,ExpressionNode>emptyMap(),args);        } else {          named = (CallToNamedArguments) args;
        }
        
        return new ComponentAllocation((QuadrigaComponent)type,named,cz);      } else {
        errorLog.insertError("Symbol " + symbolName + " is not a Component", cz);      }    } else {      errorLog.insertError("Symbol " + symbolName + " is not a Type", cz);
    }
    QuadrigaComponent component = new ProxyComponent(symbolName);
    CallToNamedArguments named = new CallToNamedArguments(Collections.<String,ExpressionNode>emptyMap(),args);
    return new ComponentAllocation(component,named,cz);  }}

ApplyPrototypeToEntity EntityInitialization(ExpressionNode entity):
{
  List<Token> name;
  CodeZone cz, argsZone;
  Token t;
  Map<String,ExpressionNode> namedArguments = new HashMap<String,ExpressionNode>();
  Map<QuadrigaComponent,CallToNamedArguments> componentArguments = new HashMap<QuadrigaComponent,CallToNamedArguments>();}
{
  name=Name() t="("
  {
    cz = new CodeZoneClass(name.get(0), t,file);
    argsZone = new CodeZoneClass(t,file);
    String prototypeName = Utils.getName(name);
    BaseSymbol symbol = symbolTable.findSymbol(prototypeName);
    QuadrigaPrototype prototype;
    if(symbol != null && symbol instanceof TypeSymbol) {
      BaseType type = ((TypeSymbol)symbol).type;
      if(type instanceof QuadrigaPrototype) {
        prototype = ((QuadrigaPrototype)type);      } else {
        errorLog.insertError("Symbol " + prototypeName + " is not a Prototype",cz);
        prototype = new ProxyPrototype(prototypeName);
        symbolTable.addSymbol(new TypeSymbol(prototype));      }    } else {
      errorLog.insertError("Symbol " + prototypeName + " is not a Type",cz);
      prototype = new ProxyPrototype(prototypeName);
      symbolTable.addSymbol(new TypeSymbol(prototype));    }  }
  [  PrototypeArgument(namedArguments,componentArguments)
     ("," PrototypeArgument(namedArguments,componentArguments))*
  ]
  t=")"
  {
    cz = new CodeZoneClass(cz, t);
    argsZone = new CodeZoneClass(argsZone,t);
    return new ApplyPrototypeToEntity(
                        entity,
                        prototype,
                        new CallToNamedArguments(namedArguments,argsZone),
                        componentArguments,
                        cz);  }}

void PrototypeArgument(Map<String,ExpressionNode> namedArguments, Map<QuadrigaComponent,CallToNamedArguments> componentArguments):
{
  ExpressionNode expression;
  Token t;}{
  LOOKAHEAD(< IDENTIFIER > ":")
  t=< IDENTIFIER > ":" expression=Expression()
  {
    namedArguments.put(t.image, expression);
  }
| Name() ":" Expression()}

QuadrigaFunction QuadrigaUpdate():
{
  List<ParameterClass > parameters;

  
  symbolTable.newContext();

  BlockCode.TmpBlockCode prevBlock = localBlock;
  
  BlockCode code;
  Token t;}{
  t="@update"
  { localBlock = new BlockCode.TmpBlockCode(t,file); }
  parameters = FormalParameters()
  code = Block()

  {
    localBlock.addStatement(code);
    localBlock.setEndCode(code);
    code = localBlock.transformToBlockCode();
    localBlock = prevBlock;
    symbolTable.deleteContext();

    return new QuadrigaFunction(parameters, code, code);  }}